from .django_adapter import (
    django_geospatial_service,
    django_postgis_repository,
    filter_queryset_by_bbox,
    filter_queryset_by_distance,
    filter_queryset_by_polygon,
    filter_queryset_contains_point,
    filter_queryset_intersects,
    table_ref_from_queryset,
)
from .filters import RadiusFilter, SpatialFilter
from .models import SpatialModelMixin
from .policy import (
    DEFAULT_GEOMETRY_BBOX_FIELDS,
    DEFAULT_GEOMETRY_CENTROID_FIELDS,
    DEFAULT_GEOMETRY_FIELD_NAME,
    DEFAULT_GEOMETRY_SRID_FIELD_NAME,
    DEFAULT_GEOMETRY_TYPE_FIELD_NAME,
    DEFAULT_SRID,
    SUPPORTED_SPATIAL_FILTERS,
    SUPPORTED_GEOMETRY_TYPES,
    supported_geometry_types,
)
from .query import filter_by_bbox, filter_by_distance, filter_by_polygon, filter_contains_point, intersects
from .repository import GeospatialRepository, PostgisGeospatialRepository, PostgisStatus, PostgisUnavailableError, SpatialTableRef
from .service import GeospatialService
from .utils import (
    BBox,
    Point,
    compute_centroid,
    ensure_srid,
    extract_bbox,
    from_geojson,
    normalize_geometry,
    point_in_polygon,
    polygon_intersects,
    to_geojson,
)

__all__ = [
    "BBox",
    "DEFAULT_GEOMETRY_BBOX_FIELDS",
    "DEFAULT_GEOMETRY_CENTROID_FIELDS",
    "DEFAULT_GEOMETRY_FIELD_NAME",
    "DEFAULT_GEOMETRY_SRID_FIELD_NAME",
    "DEFAULT_GEOMETRY_TYPE_FIELD_NAME",
    "DEFAULT_SRID",
    "GeospatialRepository",
    "GeospatialService",
    "PostgisGeospatialRepository",
    "PostgisStatus",
    "PostgisUnavailableError",
    "Point",
    "RadiusFilter",
    "SpatialTableRef",
    "SUPPORTED_GEOMETRY_TYPES",
    "SUPPORTED_SPATIAL_FILTERS",
    "SpatialFilter",
    "SpatialModelMixin",
    "compute_centroid",
    "django_geospatial_service",
    "django_postgis_repository",
    "ensure_srid",
    "extract_bbox",
    "filter_by_bbox",
    "filter_by_distance",
    "filter_by_polygon",
    "filter_contains_point",
    "filter_queryset_by_bbox",
    "filter_queryset_by_distance",
    "filter_queryset_by_polygon",
    "filter_queryset_contains_point",
    "filter_queryset_intersects",
    "from_geojson",
    "intersects",
    "normalize_geometry",
    "point_in_polygon",
    "polygon_intersects",
    "supported_geometry_types",
    "table_ref_from_queryset",
    "to_geojson",
]
