import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path

from xyn_orchestrator.blueprints import (
    blueprint_detail_view,
    blueprint_list_view,
    blueprint_studio_view,
    bundle_detail_view,
    bundle_list_view,
    capability_detail_view,
    capability_list_view,
    context_pack_activate,
    context_pack_deactivate,
    context_pack_defaults,
    context_pack_detail,
    list_context_packs,
    create_draft_session,
    enqueue_draft_generation,
    enqueue_draft_revision,
    resolve_draft_session_context,
    extract_release_target,
    save_draft_session,
    snapshot_draft_session,
    publish_draft_session,
    submit_draft_session,
    list_draft_session_revisions,
    list_draft_session_voice_notes,
    enqueue_transcription,
    get_bundle,
    get_capability,
    get_draft_session,
    get_voice_note,
    internal_draft_session,
    internal_draft_session_context,
    internal_draft_session_error,
    internal_draft_session_status,
    internal_draft_session_update,
    internal_ai_config,
    internal_openai_config,
    internal_registry_sync,
    internal_registry_detail,
    internal_release_plan_generate,
    internal_release_plan_detail,
    internal_release_plan_upsert,
    internal_release_target_deploy_manifest,
    internal_release_target_deploy_release,
    internal_release_upsert,
    internal_release_resolve,
    internal_release_target_current_release,
    internal_release_target_check_drift,
    internal_releases_latest,
    internal_release_target_deploy_latest,
    internal_release_target_rollback_last_success,
    internal_releases_retention_report,
    internal_artifacts_orphans_report,
    internal_ecr_gc_report,
    internal_releases_gc,
    internal_artifacts_gc,
    internal_release_promote,
    internal_release_plan_deploy_state,
    internal_deployments,
    internal_deployment_detail,
    internal_deployment_rollback,
    internal_release_create,
    internal_instance_detail,
    internal_instance_state,
    internal_instance_detail,
    internal_instance_state,
    internal_release_create,
    internal_run_artifact,
    internal_run_update,
    internal_run_commands,
    internal_run_commands,
    internal_context_resolve,
    internal_dev_task_detail,
    internal_dev_task_claim,
    internal_dev_task_complete,
    internal_registry_sync,
    internal_release_plan_generate,
    internal_run_artifact,
    internal_run_update,
    internal_voice_note,
    internal_voice_note_audio,
    internal_voice_note_error,
    internal_voice_note_status,
    internal_voice_note_transcript,
    list_bundles,
    list_capabilities,
    module_detail_view,
    module_list_view,
    new_draft_session_view,
    instantiate_blueprint,
    upload_voice_note,
)
from xyn_orchestrator.provisioning_views import (
    bootstrap_log_view,
    destroy_instance_view,
    get_instance,
    instance_containers_view,
    list_instances,
    retry_instance_view,
)
from xyn_orchestrator.public_views import public_article_detail, public_articles
from xyn_orchestrator.ems_canvas import (
    ems_devices_table,
    ems_registrations_table,
    ems_device_status_rollup_table,
    ems_registrations_timeseries_table,
    ems_dataset_schema,
)
from xyn_orchestrator.xyn_api import (
    blueprints_collection,
    blueprint_detail,
    blueprint_revise,
    blueprint_publish,
    blueprint_archive,
    blueprint_deprovision,
    blueprint_deprovision_plan,
    blueprint_runs,
    blueprint_submit,
    blueprint_draft_sessions,
    blueprint_voice_notes,
    environments_collection,
    environment_detail,
    control_plane_state,
    control_plane_deploy,
    control_plane_rollback,
    modules_collection,
    module_detail,
    registries_collection,
    registry_detail,
    registry_sync,
    release_plans_collection,
    release_plan_detail,
    release_plan_generate,
    release_plan_deployments,
    release_plan_reconcile,
    releases_collection,
    release_detail,
    releases_bulk_delete,
    releases_collection,
    release_detail,
    release_targets_collection,
    release_target_detail,
    map_collection,
    release_target_deploy_latest_action,
    release_target_rollback_last_success_action,
    release_target_check_drift_action,
    runs_collection,
    run_detail,
    run_logs,
    run_artifacts,
    run_commands,
    dev_tasks_collection,
    dev_task_detail,
    dev_task_run,
    dev_task_cancel,
    dev_task_retry,
    dev_task_retry,
    blueprint_dev_tasks,
    oidc_exchange,
    auth_login,
    workspace_auth_login,
    workspace_auth_callback,
    workspace_auth_login_api,
    workspace_auth_callback_api,
    auth_local_login,
    auth_callback,
    auth_logout,
    auth_session_check,
    preview_enable,
    preview_disable,
    preview_status,
    access_registry,
    access_users_collection,
    access_user_roles,
    access_user_effective,
    access_role_detail,
    seed_packs_collection,
    seed_pack_detail,
    seed_apply,
    api_me,
    tenants_collection,
    tenant_detail,
    tenant_contacts_collection,
    contact_detail,
    identities_collection,
    role_bindings_collection,
    role_binding_detail,
    workspaces_collection,
    docs_collection,
    docs_by_route,
    doc_detail,
    doc_detail_by_slug,
    doc_publish,
    articles_collection,
    article_categories_collection,
    article_category_detail,
    article_category_bindings_collection,
    article_category_binding_detail,
    article_detail,
    article_bindings_collection,
    article_binding_detail,
    article_revisions_collection,
    article_convert_html_to_markdown,
    article_transition,
    article_video_initialize,
    article_video_ai_config,
    article_video_generate_script,
    article_video_generate_storyboard,
    article_video_generate_visual_prompts,
    article_video_generate_narration,
    article_video_generate_title_description,
    article_video_renders_collection,
    article_video_export_package,
    video_adapters_collection,
    video_adapter_test_connection,
    video_adapter_configs_collection,
    video_adapter_config_detail,
    artifacts_collection,
    artifacts_catalog_collection,
    artifact_detail,
    artifact_activity,
    artifact_raw_metadata,
    artifact_raw_artifact_json,
    artifact_raw_files,
    artifact_raw_file,
    artifact_by_slug_detail,
    artifact_by_slug_files,
    artifact_surfaces_collection,
    artifact_runtime_roles_collection,
    artifact_surfaces_nav,
    artifact_surface_resolve,
    artifact_surface_registries,
    artifact_bindings_collection,
    artifact_binding_detail,
    artifact_packages_collection,
    artifact_package_detail,
    artifact_package_raw_manifest,
    artifact_package_raw_tree,
    artifact_package_raw_file,
    artifact_package_validate,
    artifact_package_install,
    artifact_install_receipts_collection,
    artifact_export_package,
    artifact_canonize_to_blueprint,
    artifacts_create_draft_session,
    artifacts_create_blueprint,
    ledger_collection,
    ledger_summary_by_user,
    ledger_summary_by_artifact,
    workflows_collection,
    workflow_detail,
    workflow_spec_update,
    workflow_transition,
    workflow_run_start,
    workflow_run_event,
    workflow_run_complete,
    intent_scripts_collection,
    intent_script_detail,
    intent_script_generate,
    workflows_actions_collection,
    workflows_actions_execute,
    video_render_detail,
    video_render_asset_download,
    video_render_cancel,
    video_render_retry,
    internal_video_render_detail,
    internal_video_render_status,
    internal_video_render_complete,
    internal_video_render_error,
    internal_secret_resolve,
    tour_detail,
    ai_purposes_collection,
    ai_purpose_detail,
    ai_bootstrap_status,
    ai_providers_collection,
    ai_credentials_collection,
    ai_credential_detail,
    ai_model_configs_collection,
    ai_model_config_detail,
    ai_model_config_compat,
    ai_agents_collection,
    ai_agent_detail,
    xyn_intent_resolve,
    xyn_intent_apply,
    xyn_intent_options,
    ai_invoke,
    ai_activity,
    internal_workspace_artifacts_collection,
    internal_ai_bootstrap_default_agent,
    workspace_artifacts_collection,
    workspace_artifact_detail,
    workspace_artifact_publish,
    workspace_artifact_deprecate,
    workspace_artifact_reactions_collection,
    workspace_artifact_comments_collection,
    workspace_artifact_comment_detail,
    workspace_activity,
    workspace_memberships_collection,
    workspace_membership_detail,
    workspace_members_collection,
    workspace_member_detail,
    workspace_auth_policy_detail,
    workspace_auth_policy_test_discovery,
    workspace_detail,
    tenants_public,
    my_profile,
    tenant_memberships_collection,
    tenant_membership_detail,
    tenant_branding_public,
    tenant_branding_update,
    tenant_devices_collection,
    device_detail,
    device_actions_collection,
    actions_collection,
    action_detail,
    action_confirm,
    action_ratify,
    action_execute,
    action_receipts_collection,
    set_active_tenant,
    internal_oidc_config,
    secret_stores_collection,
    secret_store_detail,
    secret_store_set_default,
    secret_refs_collection,
    secrets_collection,
    secret_update,
    reports_collection,
    report_detail,
    platform_config_collection,
    oidc_config,
    oidc_authorize,
    oidc_callback,
    whoami,
    identity_providers_collection,
    identity_provider_detail,
    identity_provider_test,
    oidc_app_clients_collection,
    oidc_app_client_detail,
    platform_branding,
    platform_app_branding,
    public_branding,
    branding_tokens,
    branding_theme_css,
)
from web.public_views import (
    public_home,
    public_menu,
    public_page_detail,
    public_page_sections,
    public_pages,
    public_site_config,
)

ENABLE_BLUEPRINTS_LEGACY = os.getenv("XYN_ENABLE_BLUEPRINTS_LEGACY", "false").strip().lower() in {"1", "true", "yes"}
def healthcheck(_request):
    return JsonResponse(
        {"status": "ok", "admin": "/admin/", "xyn_orchestrator": "/api/articles/"},
    )

urlpatterns = [
    path("", healthcheck),
    path("api/v1/reports", reports_collection),
    path("api/v1/reports/<uuid:report_id>", report_detail),
    path("api/v1/platform-config", platform_config_collection),
    path("api/ems/devices", ems_devices_table),
    path("api/ems/registrations", ems_registrations_table),
    path("api/ems/reports/device-status-rollup", ems_device_status_rollup_table),
    path("api/ems/reports/registrations-timeseries", ems_registrations_timeseries_table),
    path("api/ems/datasets/<str:dataset>/schema", ems_dataset_schema),
    path("admin/", admin.site.urls),
    path("api/", include("xyn_orchestrator.urls")),
    path("xyn/api/public/menu", public_menu),
    path("xyn/api/public/pages", public_pages),
    path("xyn/api/public/pages/<slug:slug>", public_page_detail),
    path("xyn/api/public/pages/<slug:slug>/sections", public_page_sections),
    path("xyn/api/public/home", public_home),
    path("xyn/api/public/site", public_site_config),
    path("xyn/api/public/articles", public_articles),
    path("xyn/api/public/articles/<slug:slug>", public_article_detail),
    path("xyn/api/auth/oidc/exchange", oidc_exchange),
    path("xyn/api/auth/oidc/config", oidc_config),
    path("xyn/api/auth/oidc/<str:provider_id>/authorize", oidc_authorize),
    path("xyn/api/auth/oidc/<str:provider_id>/callback", oidc_callback),
    path("xyn/api/auth/whoami", whoami),
    path("xyn/api/me", api_me),
    path("xyn/api/preview/enable", preview_enable),
    path("xyn/api/preview/disable", preview_disable),
    path("xyn/api/preview/status", preview_status),
    path("xyn/api/access/registry", access_registry),
    path("xyn/api/access/users", access_users_collection),
    path("xyn/api/access/users/<uuid:user_id>/roles", access_user_roles),
    path("xyn/api/access/users/<uuid:user_id>/effective", access_user_effective),
    path("xyn/api/access/roles/<str:role_id>", access_role_detail),
    path("xyn/api/seeds/packs", seed_packs_collection),
    path("xyn/api/seeds/packs/<slug:slug>", seed_pack_detail),
    path("xyn/api/seeds/apply", seed_apply),
    path("xyn/api/docs", docs_collection),
    path("xyn/api/docs/by-route", docs_by_route),
    path("xyn/api/docs/<uuid:doc_id>", doc_detail),
    path("xyn/api/docs/<uuid:doc_id>/publish", doc_publish),
    path("xyn/api/docs/slug/<slug:slug>", doc_detail_by_slug),
    path("xyn/api/articles", articles_collection),
    path("xyn/api/articles/categories", article_categories_collection),
    path("xyn/api/articles/categories/<slug:category_slug>", article_category_detail),
    path("xyn/api/articles/categories/<slug:category_slug>/bindings", article_category_bindings_collection),
    path("xyn/api/articles/categories/<slug:category_slug>/bindings/<uuid:binding_id>", article_category_binding_detail),
    path("xyn/api/articles/<uuid:article_id>", article_detail),
    path("xyn/api/articles/<uuid:article_id>/bindings", article_bindings_collection),
    path("xyn/api/articles/<uuid:article_id>/bindings/<uuid:binding_id>", article_binding_detail),
    path("xyn/api/articles/<uuid:article_id>/revisions", article_revisions_collection),
    path("xyn/api/articles/<uuid:article_id>/convert-html", article_convert_html_to_markdown),
    path("xyn/api/articles/<uuid:article_id>/transition", article_transition),
    path("xyn/api/articles/<uuid:article_id>/video/initialize", article_video_initialize),
    path("xyn/api/articles/<uuid:article_id>/video/ai-config", article_video_ai_config),
    path("xyn/api/articles/<uuid:article_id>/video/generate-script", article_video_generate_script),
    path("xyn/api/articles/<uuid:article_id>/video/generate-storyboard", article_video_generate_storyboard),
    path("xyn/api/articles/<uuid:article_id>/video/generate-visual-prompts", article_video_generate_visual_prompts),
    path("xyn/api/articles/<uuid:article_id>/video/generate-narration", article_video_generate_narration),
    path("xyn/api/articles/<uuid:article_id>/video/generate-title-description", article_video_generate_title_description),
    path("xyn/api/articles/<uuid:article_id>/video/renders", article_video_renders_collection),
    path("xyn/api/articles/<uuid:article_id>/video/render", article_video_renders_collection),
    path("xyn/api/articles/<uuid:article_id>/video/export-package", article_video_export_package),
    path("xyn/api/video/adapters", video_adapters_collection),
    path("xyn/api/video/adapters/test", video_adapter_test_connection),
    path("xyn/api/video/adapter-configs", video_adapter_configs_collection),
    path("xyn/api/video/adapter-configs/<uuid:artifact_id>", video_adapter_config_detail),
    path("xyn/api/artifacts/catalog", artifacts_catalog_collection),
    path("xyn/api/artifacts", artifacts_collection),
    path("xyn/api/artifacts/<uuid:artifact_id>", artifact_detail),
    path("xyn/api/artifacts/<uuid:artifact_id>/activity", artifact_activity),
    path("xyn/api/artifacts/<uuid:artifact_id>/raw/metadata", artifact_raw_metadata),
    path("xyn/api/artifacts/<uuid:artifact_id>/raw/artifact-json", artifact_raw_artifact_json),
    path("xyn/api/artifacts/<uuid:artifact_id>/raw/files", artifact_raw_files),
    path("xyn/api/artifacts/<uuid:artifact_id>/raw/file", artifact_raw_file),
    path("xyn/api/artifacts/slug/<str:artifact_slug>", artifact_by_slug_detail),
    path("xyn/api/artifacts/slug/<str:artifact_slug>/files", artifact_by_slug_files),
    path("xyn/api/artifacts/<uuid:artifact_id>/surfaces", artifact_surfaces_collection),
    path("xyn/api/artifacts/<uuid:artifact_id>/runtime-roles", artifact_runtime_roles_collection),
    path("xyn/api/artifacts/<uuid:artifact_id>/export-package", artifact_export_package),
    path("xyn/api/artifacts/bindings", artifact_bindings_collection),
    path("xyn/api/artifacts/bindings/<uuid:binding_id>", artifact_binding_detail),
    path("xyn/api/artifacts/packages/import", artifact_packages_collection),
    path("xyn/api/artifacts/packages", artifact_packages_collection),
    path("xyn/api/artifacts/packages/<uuid:package_id>", artifact_package_detail),
    path("xyn/api/artifacts/packages/<uuid:package_id>/raw/manifest", artifact_package_raw_manifest),
    path("xyn/api/artifacts/packages/<uuid:package_id>/raw/tree", artifact_package_raw_tree),
    path("xyn/api/artifacts/packages/<uuid:package_id>/raw/file", artifact_package_raw_file),
    path("xyn/api/artifacts/packages/<uuid:package_id>/validate", artifact_package_validate),
    path("xyn/api/artifacts/packages/<uuid:package_id>/install", artifact_package_install),
    path("xyn/api/artifacts/install-receipts", artifact_install_receipts_collection),
    path("xyn/api/artifact-surfaces/nav", artifact_surfaces_nav),
    path("xyn/api/artifact-surfaces/resolve", artifact_surface_resolve),
    path("xyn/api/artifact-surfaces/registries", artifact_surface_registries),
    path("xyn/api/ledger", ledger_collection),
    path("xyn/api/ledger/summary/by-user", ledger_summary_by_user),
    path("xyn/api/ledger/summary/by-artifact", ledger_summary_by_artifact),
    path("xyn/api/workflows", workflows_collection),
    path("xyn/api/workflows/actions", workflows_actions_collection),
    path("xyn/api/workflows/actions/execute", workflows_actions_execute),
    path("xyn/api/workflows/<uuid:workflow_id>", workflow_detail),
    path("xyn/api/workflows/<uuid:workflow_id>/spec", workflow_spec_update),
    path("xyn/api/workflows/<uuid:workflow_id>/transition", workflow_transition),
    path("xyn/api/workflows/<uuid:workflow_id>/run/start", workflow_run_start),
    path("xyn/api/workflows/<uuid:workflow_id>/run/<uuid:run_id>/event", workflow_run_event),
    path("xyn/api/workflows/<uuid:workflow_id>/run/<uuid:run_id>/complete", workflow_run_complete),
    path("xyn/api/video-renders/<uuid:render_id>", video_render_detail),
    path("xyn/api/video-renders/<uuid:render_id>/assets/<int:asset_index>/download", video_render_asset_download),
    path("xyn/api/video-renders/<uuid:render_id>/cancel", video_render_cancel),
    path("xyn/api/video-renders/<uuid:render_id>/retry", video_render_retry),
    path("xyn/api/tours/<slug:tour_slug>", tour_detail),
    path("xyn/api/intent-scripts", intent_scripts_collection),
    path("xyn/api/intent-scripts/generate", intent_script_generate),
    path("xyn/api/intent-scripts/<uuid:script_id>", intent_script_detail),
    path("xyn/api/ai/purposes", ai_purposes_collection),
    path("xyn/api/ai/purposes/<slug:purpose_slug>", ai_purpose_detail),
    path("xyn/api/ai/bootstrap-status", ai_bootstrap_status),
    path("xyn/api/ai/providers", ai_providers_collection),
    path("xyn/api/ai/credentials", ai_credentials_collection),
    path("xyn/api/ai/credentials/<uuid:credential_id>", ai_credential_detail),
    path("xyn/api/ai/model-configs", ai_model_configs_collection),
    path("xyn/api/ai/model-configs/<uuid:model_config_id>", ai_model_config_detail),
    path("xyn/api/ai/model-configs/<uuid:model_config_id>/compat", ai_model_config_compat),
    path("xyn/api/ai/agents", ai_agents_collection),
    path("xyn/api/ai/agents/<uuid:agent_id>", ai_agent_detail),
    path("xyn/api/xyn/intent/resolve", xyn_intent_resolve),
    path("xyn/api/xyn/intent/apply", xyn_intent_apply),
    path("xyn/api/xyn/intent/options", xyn_intent_options),
    path("xyn/api/ai/invoke", ai_invoke),
    path("xyn/api/ai/activity", ai_activity),
    path("xyn/api/workspaces", workspaces_collection),
    path("api/workspaces", workspaces_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>", workspace_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts", workspace_artifacts_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>", workspace_artifact_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>/publish", workspace_artifact_publish),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>/deprecate", workspace_artifact_deprecate),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>/reactions", workspace_artifact_reactions_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>/comments", workspace_artifact_comments_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>/artifacts/<uuid:artifact_id>/comments/<uuid:comment_id>", workspace_artifact_comment_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/activity", workspace_activity),
    path("xyn/api/workspaces/<uuid:workspace_id>/memberships", workspace_memberships_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>/memberships/<uuid:membership_id>", workspace_membership_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/members", workspace_members_collection),
    path("xyn/api/workspaces/<uuid:workspace_id>/members/<uuid:member_id>", workspace_member_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/auth-policy", workspace_auth_policy_detail),
    path("xyn/api/workspaces/<uuid:workspace_id>/auth-policy/test-discovery", workspace_auth_policy_test_discovery),
    path("xyn/api/workspaces/<uuid:workspace_id>/auth/login", workspace_auth_login_api),
    path("xyn/api/workspaces/<uuid:workspace_id>/auth/callback", workspace_auth_callback_api),
    path("xyn/internal/workspaces/<uuid:workspace_id>/artifacts", internal_workspace_artifacts_collection),
    path("xyn/internal/ai/bootstrap-default-agent", internal_ai_bootstrap_default_agent),
    path("xyn/api/tenants", tenants_public),
    path("xyn/api/tenant/devices", tenant_devices_collection),
    path("xyn/api/devices/<uuid:device_id>", device_detail),
    path("xyn/api/devices/<uuid:device_id>/actions", device_actions_collection),
    path("xyn/api/actions", actions_collection),
    path("xyn/api/actions/<uuid:action_id>", action_detail),
    path("xyn/api/actions/<uuid:action_id>/confirm", action_confirm),
    path("xyn/api/actions/<uuid:action_id>/ratify", action_ratify),
    path("xyn/api/actions/<uuid:action_id>/execute", action_execute),
    path("xyn/api/actions/<uuid:action_id>/receipts", action_receipts_collection),
    path("xyn/api/tenants/<uuid:tenant_id>/branding", tenant_branding_public),
    path("xyn/api/my/profile", my_profile),
    path("xyn/api/my/active-tenant", set_active_tenant),
    path("xyn/internal/auth/oidc/config", internal_oidc_config),
    path("xyn/internal/secret-stores", secret_stores_collection),
    path("xyn/internal/secret-stores/<uuid:store_id>", secret_store_detail),
    path("xyn/internal/secret-stores/<uuid:store_id>/set_default", secret_store_set_default),
    path("xyn/internal/secret-refs", secret_refs_collection),
    path("xyn/internal/secrets", secrets_collection),
    path("xyn/internal/secrets/<uuid:secret_ref_id>", secret_update),
    path("xyn/internal/tenants", tenants_collection),
    path("xyn/internal/tenants/<uuid:tenant_id>", tenant_detail),
    path("xyn/internal/tenants/<uuid:tenant_id>/contacts", tenant_contacts_collection),
    path("xyn/internal/tenants/<uuid:tenant_id>/memberships", tenant_memberships_collection),
    path("xyn/internal/contacts/<uuid:contact_id>", contact_detail),
    path("xyn/internal/memberships/<uuid:membership_id>", tenant_membership_detail),
    path("xyn/internal/tenants/<uuid:tenant_id>/branding", tenant_branding_update),
    path("xyn/api/platform/identity-providers", identity_providers_collection),
    path("xyn/api/platform/identity-providers/<str:provider_id>", identity_provider_detail),
    path("xyn/api/platform/identity-providers/<str:provider_id>/test", identity_provider_test),
    path("xyn/api/platform/oidc-app-clients", oidc_app_clients_collection),
    path("xyn/api/platform/oidc-app-clients/<uuid:client_id>", oidc_app_client_detail),
    path("xyn/api/platform/branding", platform_branding),
    path("xyn/api/platform/branding/apps/<str:app_id>", platform_app_branding),
    path("xyn/api/public/branding", public_branding),
    path("xyn/api/branding/tokens", branding_tokens),
    path("xyn/api/branding/theme.css", branding_theme_css),
    path("xyn/internal/identities", identities_collection),
    path("xyn/internal/role_bindings", role_bindings_collection),
    path("xyn/internal/role_bindings/<uuid:binding_id>", role_binding_detail),
    path("auth/login", auth_login),
    path("auth/local-login", auth_local_login),
    path("auth/callback", auth_callback),
    path("w/<uuid:workspace_id>/auth/login", workspace_auth_login),
    path("w/<uuid:workspace_id>/auth/callback", workspace_auth_callback),
    path("auth/logout", auth_logout),
    path("xyn/api/auth/session-check", auth_session_check),
    path("xyn/modules/", module_list_view, name="module-list"),
    path("xyn/modules/<uuid:module_id>/", module_detail_view, name="module-detail"),
    path("xyn/bundles/", bundle_list_view, name="bundle-list"),
    path("xyn/bundles/<uuid:bundle_id>/", bundle_detail_view, name="bundle-detail"),
    path("xyn/capabilities/", capability_list_view, name="capability-list"),
    path("xyn/capabilities/<uuid:capability_id>/", capability_detail_view, name="capability-detail"),
    path("xyn/api/modules", modules_collection),
    path("xyn/api/modules/<path:module_ref>", module_detail),
    path("xyn/api/bundles", list_bundles),
    path("xyn/api/bundles/<path:bundle_ref>", get_bundle),
    path("xyn/api/registries", registries_collection),
    path("xyn/api/registries/<uuid:registry_id>", registry_detail),
    path("xyn/api/registries/<uuid:registry_id>/sync", registry_sync),
    path("xyn/api/release-plans", release_plans_collection),
    path("xyn/api/release-plans/reconcile", release_plan_reconcile),
    path("xyn/api/release-plans/<uuid:plan_id>", release_plan_detail),
    path("xyn/api/release-plans/<uuid:plan_id>/deployments", release_plan_deployments),
    path("xyn/api/release-plans/<uuid:plan_id>/generate", release_plan_generate),
    path("xyn/api/release-targets", release_targets_collection),
    path("xyn/api/release-targets/<uuid:target_id>", release_target_detail),
    path("xyn/api/release-targets/<uuid:target_id>/deploy_latest", release_target_deploy_latest_action),
    path("xyn/api/release-targets/<uuid:target_id>/rollback_last_success", release_target_rollback_last_success_action),
    path("xyn/api/release-targets/<uuid:target_id>/check_drift", release_target_check_drift_action),
    path("xyn/api/map", map_collection),
    path("xyn/api/releases", releases_collection),
    path("xyn/api/releases/bulk-delete", releases_bulk_delete),
    path("xyn/api/releases/<uuid:release_id>", release_detail),
    path("xyn/api/environments", environments_collection),
    path("xyn/api/environments/<uuid:env_id>", environment_detail),
    path("xyn/api/control-plane/state", control_plane_state),
    path("xyn/api/control-plane/deploy", control_plane_deploy),
    path("xyn/api/control-plane/rollback", control_plane_rollback),
    path("xyn/api/runs", runs_collection),
    path("api/runs", runs_collection),
    path("xyn/api/runs/<uuid:run_id>", run_detail),
    path("api/runs/<uuid:run_id>", run_detail),
    path("xyn/api/runs/<uuid:run_id>/logs", run_logs),
    path("xyn/api/runs/<uuid:run_id>/artifacts", run_artifacts),
    path("xyn/api/runs/<uuid:run_id>/commands", run_commands),
    path("xyn/api/dev-tasks", dev_tasks_collection),
    path("xyn/api/dev-tasks/<uuid:task_id>", dev_task_detail),
    path("xyn/api/dev-tasks/<uuid:task_id>/run", dev_task_run),
    path("xyn/api/dev-tasks/<uuid:task_id>/cancel", dev_task_cancel),
    path("xyn/api/dev-tasks/<uuid:task_id>/retry", dev_task_retry),
    path("xyn/api/capabilities", list_capabilities),
    path("xyn/api/capabilities/<path:capability_ref>", get_capability),
    path("xyn/api/context-packs", list_context_packs),
    path("xyn/api/context-pack-defaults", context_pack_defaults),
    path("xyn/api/context-packs/<uuid:pack_id>", context_pack_detail),
    path("xyn/api/context-packs/<uuid:pack_id>/activate", context_pack_activate),
    path("xyn/api/context-packs/<uuid:pack_id>/deactivate", context_pack_deactivate),
    path("xyn/api/provision/instances", list_instances),
    path("xyn/api/provision/instances/<uuid:instance_id>", get_instance),
    path("xyn/api/provision/instances/<uuid:instance_id>/destroy", destroy_instance_view),
    path("xyn/api/provision/instances/<uuid:instance_id>/retry", retry_instance_view),
    path("xyn/api/provision/instances/<uuid:instance_id>/bootstrap-log", bootstrap_log_view),
    path("xyn/api/provision/instances/<uuid:instance_id>/containers", instance_containers_view),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>", internal_voice_note),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/audio", internal_voice_note_audio),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/transcript", internal_voice_note_transcript),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/error", internal_voice_note_error),
    path("xyn/internal/voice-notes/<uuid:voice_note_id>/status", internal_voice_note_status),
    path("xyn/internal/video-renders/<uuid:render_id>", internal_video_render_detail),
    path("xyn/internal/video-renders/<uuid:render_id>/status", internal_video_render_status),
    path("xyn/internal/video-renders/<uuid:render_id>/complete", internal_video_render_complete),
    path("xyn/internal/video-renders/<uuid:render_id>/error", internal_video_render_error),
    path("xyn/internal/secrets/resolve", internal_secret_resolve),
    path("xyn/internal/ai/config", internal_ai_config),
    path("xyn/internal/openai-config", internal_openai_config),
    path("xyn/internal/context-packs/resolve", internal_context_resolve),
    path("xyn/internal/dev-tasks/<uuid:task_id>", internal_dev_task_detail),
    path("xyn/internal/dev-tasks/<uuid:task_id>/claim", internal_dev_task_claim),
    path("xyn/internal/dev-tasks/<uuid:task_id>/complete", internal_dev_task_complete),
    path("xyn/internal/runs/<uuid:run_id>", internal_run_update),
    path("xyn/internal/runs/<uuid:run_id>/artifacts", internal_run_artifact),
    path("xyn/internal/runs/<uuid:run_id>/commands", internal_run_commands),
    path("xyn/internal/registries/<uuid:registry_id>", internal_registry_detail),
    path("xyn/internal/registries/<uuid:registry_id>/sync", internal_registry_sync),
    path("xyn/internal/release-plans/<uuid:plan_id>", internal_release_plan_detail),
    path("xyn/internal/release-plans/<uuid:plan_id>/generate", internal_release_plan_generate),
    path("xyn/internal/release-plans/upsert", internal_release_plan_upsert),
    path("xyn/internal/release-plans/<uuid:plan_id>/deploy-state", internal_release_plan_deploy_state),
    path("xyn/internal/deployments", internal_deployments),
    path("xyn/internal/deployments/<uuid:deployment_id>", internal_deployment_detail),
    path("xyn/internal/deployments/<uuid:deployment_id>/rollback", internal_deployment_rollback),
    path("api/internal/deployments", internal_deployments),
    path("api/internal/deployments/<uuid:deployment_id>", internal_deployment_detail),
    path("api/internal/deployments/<uuid:deployment_id>/rollback", internal_deployment_rollback),
    path("xyn/internal/releases", internal_release_create),
    path("xyn/internal/releases/latest", internal_releases_latest),
    path("xyn/internal/releases/retention_report", internal_releases_retention_report),
    path("xyn/internal/releases/gc", internal_releases_gc),
    path("xyn/internal/releases/upsert", internal_release_upsert),
    path("xyn/internal/releases/resolve", internal_release_resolve),
    path("xyn/internal/releases/promote", internal_release_promote),
    path("xyn/internal/release-targets/<uuid:target_id>/deploy_manifest", internal_release_target_deploy_manifest),
    path("xyn/internal/release-targets/<uuid:target_id>/deploy_release", internal_release_target_deploy_release),
    path("xyn/internal/release-targets/<uuid:target_id>/deploy_latest", internal_release_target_deploy_latest),
    path("xyn/internal/release-targets/<uuid:target_id>/rollback_last_success", internal_release_target_rollback_last_success),
    path("xyn/internal/release-targets/<uuid:target_id>/current_release", internal_release_target_current_release),
    path("xyn/internal/release-targets/<uuid:target_id>/check_drift", internal_release_target_check_drift),
    path("xyn/internal/artifacts/orphans_report", internal_artifacts_orphans_report),
    path("xyn/internal/artifacts/gc", internal_artifacts_gc),
    path("xyn/internal/registry/ecr_gc_report", internal_ecr_gc_report),
    path("xyn/internal/instances/<uuid:instance_id>", internal_instance_detail),
    path("xyn/internal/instances/<uuid:instance_id>/state", internal_instance_state),
    path("accounts/", include("allauth.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if ENABLE_BLUEPRINTS_LEGACY:
    urlpatterns += [
        path("xyn/blueprints/", blueprint_list_view, name="blueprint-list"),
        path("xyn/studio/blueprints/new", new_draft_session_view, name="blueprint-session-new"),
        path("xyn/blueprints/<uuid:blueprint_id>/", blueprint_detail_view, name="blueprint-detail"),
        path("xyn/studio/blueprints/draft-sessions/<uuid:session_id>/", blueprint_studio_view, name="blueprint-studio"),
        path("xyn/api/blueprints", blueprints_collection),
        path("xyn/api/blueprints/<uuid:blueprint_id>", blueprint_detail),
        path("xyn/api/blueprints/<uuid:artifact_id>/revise", blueprint_revise),
        path("xyn/api/blueprints/<uuid:artifact_id>/publish", blueprint_publish),
        path("xyn/api/blueprints/<uuid:blueprint_id>/archive", blueprint_archive),
        path("xyn/api/blueprints/<uuid:blueprint_id>/deprovision_plan", blueprint_deprovision_plan),
        path("xyn/api/blueprints/<uuid:blueprint_id>/deprovision", blueprint_deprovision),
        path("xyn/api/blueprints/<uuid:blueprint_id>/submit", blueprint_submit),
        path("xyn/api/blueprints/<uuid:blueprint_id>/runs", blueprint_runs),
        path("xyn/api/blueprints/<uuid:blueprint_id>/draft-sessions", blueprint_draft_sessions),
        path("xyn/api/blueprints/<uuid:blueprint_id>/voice-notes", blueprint_voice_notes),
        path("xyn/api/blueprints/<uuid:blueprint_id>/instantiate", instantiate_blueprint),
        path("xyn/api/blueprints/<uuid:blueprint_id>/dev-tasks", blueprint_dev_tasks),
        path("xyn/api/artifacts/<uuid:artifact_id>/canonize-to-blueprint", artifact_canonize_to_blueprint),
        path("xyn/api/artifacts/create-draft-session", artifacts_create_draft_session),
        path("xyn/api/artifacts/create-blueprint", artifacts_create_blueprint),
        path("xyn/api/voice-notes", upload_voice_note, name="voice-note-upload"),
        path("xyn/api/voice-notes/<uuid:voice_note_id>/enqueue-transcription", enqueue_transcription),
        path("xyn/api/voice-notes/<uuid:voice_note_id>", get_voice_note),
        path("xyn/api/draft-sessions", create_draft_session, name="draft-session-create"),
        path("xyn/api/draft-sessions/<uuid:session_id>/enqueue-draft-generation", enqueue_draft_generation),
        path("xyn/api/draft-sessions/<uuid:session_id>/enqueue-draft-revision", enqueue_draft_revision),
        path("xyn/api/draft-sessions/<uuid:session_id>/resolve-context", resolve_draft_session_context),
        path("xyn/api/draft-sessions/<uuid:session_id>/extract_release_target", extract_release_target),
        path("xyn/api/draft-sessions/<uuid:session_id>/save", save_draft_session),
        path("xyn/api/draft-sessions/<uuid:session_id>/snapshot", snapshot_draft_session),
        path("xyn/api/draft-sessions/<uuid:session_id>/publish", publish_draft_session),
        path("xyn/api/draft-sessions/<uuid:session_id>/submit", submit_draft_session),
        path("xyn/api/draft-sessions/<uuid:session_id>/revisions", list_draft_session_revisions),
        path("xyn/api/draft-sessions/<uuid:session_id>/voice-notes", list_draft_session_voice_notes),
        path("xyn/api/draft-sessions/<uuid:session_id>", get_draft_session),
        path("xyn/internal/draft-sessions/<uuid:session_id>", internal_draft_session),
        path("xyn/internal/draft-sessions/<uuid:session_id>/context/resolve", internal_draft_session_context),
        path("xyn/internal/draft-sessions/<uuid:session_id>/draft", internal_draft_session_update),
        path("xyn/internal/draft-sessions/<uuid:session_id>/error", internal_draft_session_error),
        path("xyn/internal/draft-sessions/<uuid:session_id>/status", internal_draft_session_status),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
