# Generated by Django 5.2.10 on 2026-01-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0011_blueprint_voice_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintrevision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='draftsessionvoicenote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='openaiconfig',
            name='system_instructions',
            field=models.TextField(default='You are assisting in drafting technical articles for Xyence, a CTO and platform consulting firm. Output a JSON object with a title, summary, and HTML body suitable for a website article. Treat the response as a draft artifact that will be versioned in a CMS.'),
        ),
        migrations.AlterField(
            model_name='voicetranscript',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
