# Generated by Codex on 2026-01-28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("xyn_orchestrator", "0016_context_packs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionedInstance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("aws_region", models.CharField(max_length=50)),
                ("instance_id", models.CharField(blank=True, max_length=64)),
                ("instance_type", models.CharField(max_length=64)),
                ("ami_id", models.CharField(max_length=64)),
                ("security_group_id", models.CharField(blank=True, max_length=64)),
                ("subnet_id", models.CharField(blank=True, max_length=64)),
                ("vpc_id", models.CharField(blank=True, max_length=64)),
                ("public_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("private_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ssm_status", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("provisioning", "Provisioning"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                            ("terminating", "Terminating"),
                            ("terminated", "Terminated"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("tags_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioned_instances_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provisioned_instances_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
