# Generated by Django 5.2.10 on 2026-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0017_provisioned_instance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blueprintdraftsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("drafting", "Drafting"),
                    ("queued", "Queued"),
                    ("ready", "Ready"),
                    ("ready_with_errors", "Ready with errors"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("failed", "Failed"),
                ],
                default="drafting",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="capability",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="voicenote",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("queued", "Queued"),
                    ("transcribing", "Transcribing"),
                    ("transcribed", "Transcribed"),
                    ("drafting", "Drafting"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
