# Generated by Codex on 2026-02-07
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("xyn_orchestrator", "0032_alter_runcommandexecution_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseTarget",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("environment", models.CharField(blank=True, max_length=120)),
                ("target_instance_ref", models.CharField(blank=True, max_length=120)),
                ("fqdn", models.CharField(max_length=200)),
                ("dns_json", models.JSONField(blank=True, null=True)),
                ("runtime_json", models.JSONField(blank=True, null=True)),
                ("tls_json", models.JSONField(blank=True, null=True)),
                ("env_json", models.JSONField(blank=True, null=True)),
                ("secret_refs_json", models.JSONField(blank=True, null=True)),
                ("config_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_targets",
                        to="xyn_orchestrator.blueprint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_targets_created",
                        to="auth.user",
                    ),
                ),
                (
                    "target_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_targets",
                        to="xyn_orchestrator.provisionedinstance",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_targets_updated",
                        to="auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("blueprint", "name")},
            },
        ),
    ]
