# Generated by Django 5.1.5 on 2026-02-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0046_oidc_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformBranding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("brand_name", models.CharField(default="Xyn", max_length=200)),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("favicon_url", models.CharField(blank=True, max_length=500, null=True)),
                ("primary_color", models.CharField(default="#0f4c81", max_length=40)),
                ("background_color", models.CharField(default="#f5f7fb", max_length=40)),
                ("background_gradient", models.CharField(blank=True, max_length=240, null=True)),
                ("text_color", models.CharField(default="#10203a", max_length=40)),
                ("font_family", models.CharField(blank=True, max_length=120, null=True)),
                ("button_radius_px", models.IntegerField(default=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_branding_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="AppBrandingOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("app_id", models.CharField(max_length=120, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=200, null=True)),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("primary_color", models.CharField(blank=True, max_length=40, null=True)),
                ("background_color", models.CharField(blank=True, max_length=40, null=True)),
                ("background_gradient", models.CharField(blank=True, max_length=240, null=True)),
                ("text_color", models.CharField(blank=True, max_length=40, null=True)),
                ("font_family", models.CharField(blank=True, max_length=120, null=True)),
                ("button_radius_px", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_branding_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["app_id"]},
        ),
    ]
