# Generated by Django 5.2.11 on 2026-02-13 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0048_deployment_app_id_deployment_environment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretStore",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("aws_secrets_manager", "AWS Secrets Manager")],
                        default="aws_secrets_manager",
                        max_length=60,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SecretRef",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240)),
                (
                    "scope_kind",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("tenant", "Tenant"),
                            ("user", "User"),
                            ("team", "Team"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_id", models.UUIDField(blank=True, null=True)),
                ("external_ref", models.CharField(max_length=512)),
                (
                    "type",
                    models.CharField(
                        choices=[("secrets_manager", "Secrets Manager")],
                        default="secrets_manager",
                        max_length=40,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=120, null=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("metadata_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="secret_refs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_refs",
                        to="xyn_orchestrator.secretstore",
                    ),
                ),
            ],
            options={
                "ordering": ["scope_kind", "name"],
                "unique_together": {("scope_kind", "scope_id", "name")},
            },
        ),
        migrations.AddConstraint(
            model_name="secretstore",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_default=True),
                fields=("is_default",),
                name="xyn_single_default_secret_store",
            ),
        ),
    ]
