# Generated by Django 5.2.11 on 2026-02-13 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0049_secret_stores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfigDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_configs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-version"]},
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("report_type", models.CharField(choices=[("bug", "Bug"), ("feature", "Feature")], max_length=20)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[("p0", "P0"), ("p1", "P1"), ("p2", "P2"), ("p3", "P3")],
                        default="p2",
                        max_length=10,
                    ),
                ),
                ("tags_json", models.JSONField(blank=True, default=list)),
                ("context_json", models.JSONField(blank=True, default=dict)),
                ("notification_errors_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=300)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("storage_provider", models.CharField(default="local", max_length=40)),
                ("storage_bucket", models.CharField(blank=True, max_length=255)),
                ("storage_key", models.CharField(blank=True, max_length=700)),
                ("storage_path", models.CharField(blank=True, max_length=900)),
                ("storage_metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="xyn_orchestrator.report",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
