# Generated by Django 5.2.11 on 2026-02-21 13:30

import django.db.models.deletion
import os
import uuid
from django.db import migrations, models


def _seed_agent_stub(apps, schema_editor):
    ModelProvider = apps.get_model("xyn_orchestrator", "ModelProvider")
    ModelConfig = apps.get_model("xyn_orchestrator", "ModelConfig")
    AgentPurpose = apps.get_model("xyn_orchestrator", "AgentPurpose")
    AgentDefinition = apps.get_model("xyn_orchestrator", "AgentDefinition")
    AgentDefinitionPurpose = apps.get_model("xyn_orchestrator", "AgentDefinitionPurpose")

    provider_slug = str(os.environ.get("XYN_DEFAULT_MODEL_PROVIDER") or "openai").strip().lower()
    model_name = str(os.environ.get("XYN_DEFAULT_MODEL_NAME") or "gpt-4o-mini").strip()
    provider = ModelProvider.objects.filter(slug=provider_slug).first() or ModelProvider.objects.filter(slug="openai").first()
    if not provider:
        return
    config, _ = ModelConfig.objects.get_or_create(
        provider=provider,
        model_name=model_name,
        defaults={"temperature": 0.2, "max_tokens": 1200, "enabled": True},
    )
    purpose, _ = AgentPurpose.objects.get_or_create(
        slug="documentation",
        defaults={"name": "Documentation", "description": "Documentation authoring and editing", "enabled": True},
    )
    if not purpose.name:
        purpose.name = "Documentation"
        purpose.save(update_fields=["name"])
    agent, _ = AgentDefinition.objects.get_or_create(
        slug="documentation-default",
        defaults={
            "name": "Documentation Default",
            "model_config": config,
            "system_prompt_text": "You are a documentation assistant for Xyn.",
            "enabled": True,
        },
    )
    AgentDefinitionPurpose.objects.get_or_create(agent_definition=agent, purpose=purpose)


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0067_modelconfig_modelprovider_agentpurpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("api_key_encrypted", "Encrypted API key"), ("env_ref", "Environment variable")],
                        default="env_ref",
                        max_length=40,
                    ),
                ),
                ("api_key_encrypted", models.TextField(blank=True, null=True)),
                ("env_var_name", models.CharField(blank=True, max_length=160)),
                ("is_default", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="xyn_orchestrator.modelprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider__slug", "-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("system_prompt_text", models.TextField(blank=True)),
                ("context_pack_refs_json", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_definitions",
                        to="xyn_orchestrator.modelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="AgentDefinitionPurpose",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "agent_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purpose_links",
                        to="xyn_orchestrator.agentdefinition",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_links",
                        to="xyn_orchestrator.agentpurpose",
                    ),
                ),
            ],
            options={
                "ordering": ["agent_definition__slug", "purpose__slug"],
                "unique_together": {("agent_definition", "purpose")},
            },
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="purposes",
            field=models.ManyToManyField(related_name="agent_definitions", through="xyn_orchestrator.AgentDefinitionPurpose", to="xyn_orchestrator.agentpurpose"),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="credential",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="model_configs", to="xyn_orchestrator.providercredential"),
        ),
        migrations.AddField(
            model_name="modelconfig",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agentpurpose",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="agentpurpose",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(_seed_agent_stub, migrations.RunPython.noop),
    ]
