# Generated by Codex on 2026-01-28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("xyn_orchestrator", "0014_add_job_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintrevision",
            name="blueprint_kind",
            field=models.CharField(
                choices=[("solution", "Solution"), ("module", "Module"), ("bundle", "Bundle")],
                default="solution",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blueprintdraftsession",
            name="blueprint_kind",
            field=models.CharField(
                choices=[("solution", "Solution"), ("module", "Module"), ("bundle", "Bundle")],
                default="solution",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("namespace", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("fqn", models.CharField(max_length=240, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("adapter", "Adapter"),
                            ("service", "Service"),
                            ("ui", "UI"),
                            ("workflow", "Workflow"),
                            ("schema", "Schema"),
                            ("infra", "Infra"),
                            ("lib", "Lib"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_version", models.CharField(max_length=64)),
                ("latest_module_spec_json", models.JSONField(blank=True, null=True)),
                ("capabilities_provided_json", models.JSONField(blank=True, null=True)),
                ("interfaces_json", models.JSONField(blank=True, null=True)),
                ("dependencies_json", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deprecated", "Deprecated"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["namespace", "name"],
                "unique_together": {("namespace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("namespace", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("fqn", models.CharField(max_length=240, unique=True)),
                ("current_version", models.CharField(max_length=64)),
                ("bundle_spec_json", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deprecated", "Deprecated"), ("archived", "Archived")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundles_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["namespace", "name"],
                "unique_together": {("namespace", "name")},
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("version", models.CharField(default="1.0", max_length=64)),
                ("profiles_json", models.JSONField(blank=True, null=True)),
                ("capability_spec_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReleasePlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("module", "Module"), ("bundle", "Bundle"), ("release", "Release")],
                        max_length=20,
                    ),
                ),
                ("target_fqn", models.CharField(max_length=240)),
                ("from_version", models.CharField(blank=True, max_length=64)),
                ("to_version", models.CharField(max_length=64)),
                ("milestones_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_plans_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
