# Generated by Codex on 2026-01-28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("xyn_orchestrator", "0015_module_bundle_capability_releaseplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintdraftsession",
            name="context_pack_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="blueprintdraftsession",
            name="context_pack_refs_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blueprintdraftsession",
            name="effective_context_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="blueprintdraftsession",
            name="effective_context_preview",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ContextPack",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("namespace", "Namespace"), ("project", "Project")],
                        max_length=20,
                    ),
                ),
                ("namespace", models.CharField(blank=True, max_length=120)),
                ("project_key", models.CharField(blank=True, max_length=120)),
                ("version", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("content_markdown", models.TextField()),
                ("applies_to_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_packs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="context_packs_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "version", "scope", "namespace", "project_key")},
            },
        ),
    ]
