# Generated by Django 5.2.11 on 2026-02-07 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0031_merge_20260206_0806"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runcommandexecution",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="devtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("codegen", "Codegen"),
                    ("module_scaffold", "Module scaffold"),
                    ("release_plan_generate", "Release plan generate"),
                    ("registry_sync", "Registry sync"),
                    ("deploy", "Deploy"),
                    ("deploy_release_plan", "Deploy release plan"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="release",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("deprecated", "Deprecated")],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="releaseplan",
            name="target_kind",
            field=models.CharField(
                choices=[("module", "Module"), ("bundle", "Bundle"), ("release", "Release"), ("blueprint", "Blueprint")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="releaseplandeployment",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="releaseplandeploystate",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="runcommandexecution",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="runcommandexecution",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
