# Generated by Codex on 2026-02-08
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0033_release_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("provider", models.CharField(max_length=50)),
                ("issuer", models.CharField(max_length=240)),
                ("subject", models.CharField(max_length=240)),
                ("email", models.CharField(max_length=240, blank=True)),
                ("display_name", models.CharField(max_length=240, blank=True)),
                ("claims_json", models.JSONField(null=True, blank=True)),
                ("last_login_at", models.DateTimeField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("issuer", "subject")},
            },
        ),
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("scope_kind", models.CharField(max_length=20, choices=[("platform", "Platform"), ("tenant", "Tenant")], default="platform")),
                ("scope_id", models.UUIDField(null=True, blank=True)),
                ("role", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_identity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="role_bindings", to="xyn_orchestrator.useridentity")),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user_identity", "scope_kind", "scope_id", "role")},
            },
        ),
    ]
