# Generated by Django 5.2.11 on 2026-02-12 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0047_platform_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='app_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='xyn_orchestrator.environment'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='health_check_details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='health_check_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rollback_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_attempts', to='xyn_orchestrator.deployment'),
        ),
        migrations.CreateModel(
            name='EnvironmentAppState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=120)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('last_good_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_env_states', to='xyn_orchestrator.release')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_states', to='xyn_orchestrator.environment')),
                ('last_deploy_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_app_states', to='xyn_orchestrator.run')),
                ('last_good_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_good_in_env_states', to='xyn_orchestrator.release')),
            ],
            options={
                'ordering': ['environment__name', 'app_id'],
                'unique_together': {('environment', 'app_id')},
            },
        ),
    ]
