# Generated by Django 5.1.5 on 2026-02-20 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("xyn_orchestrator", "0065_governed_device_actions"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="actionverifierevidence",
            new_name="xyn_orchest_draft_a_aee5db_idx",
            old_name="xyn_orchest_draft_a_4443de_idx",
        ),
        migrations.RenameIndex(
            model_name="draftaction",
            new_name="xyn_orchest_tenant__38fafa_idx",
            old_name="xyn_orchest_tenant__2621b1_idx",
        ),
        migrations.RenameIndex(
            model_name="draftaction",
            new_name="xyn_orchest_device__f810f3_idx",
            old_name="xyn_orchest_device__6b9f25_idx",
        ),
        migrations.RenameIndex(
            model_name="draftactionevent",
            new_name="xyn_orchest_draft_a_1b86b7_idx",
            old_name="xyn_orchest_draft_a_938355_idx",
        ),
    ]
