# Generated by Django 5.2.11 on 2026-02-20 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


CORE_CONCEPTS_MD = """# Core Concepts

Xyn treats durable intelligence as governed artifacts with provenance, explicit lifecycle, and auditability.

## Flow
- Design: capture intent in blueprints and modules
- Shape: iterate drafts and validate
- Package: build releases and release plans
- Run: deploy to instances and execute tasks
- Observe: inspect logs, artifacts, and activity

## Governance
- Promotion rules are explicit and logged.
- Runtime can propose, but authorized humans ratify/publish where policy requires.
- Revisions are preserved for corrigibility and audits.
"""


SUBSCRIBER_NOTES_GUIDE_MD = """# Deploy Subscriber Notes

## Golden Path
1. Open **Blueprints** and pick Subscriber Notes.
2. Go to **Drafts** and generate a draft from that blueprint.
3. Go to **Releases / Release Plans** and create a plan.
4. Open **Instances** and target `xyn-seed-dev-1`.
5. Deploy the release plan.
6. Review execution logs and artifacts in **Runs**.

## Validation
- The app is reachable over HTTPS.
- Login succeeds via configured IdP.
- Create/list/delete note actions persist.
"""


def _ensure_doc_pages(apps, schema_editor):
    Workspace = apps.get_model("xyn_orchestrator", "Workspace")
    ArtifactType = apps.get_model("xyn_orchestrator", "ArtifactType")
    Artifact = apps.get_model("xyn_orchestrator", "Artifact")
    ArtifactRevision = apps.get_model("xyn_orchestrator", "ArtifactRevision")
    ArtifactEvent = apps.get_model("xyn_orchestrator", "ArtifactEvent")

    workspace, _ = Workspace.objects.get_or_create(
        slug="platform-builder",
        defaults={"name": "Platform Builder", "description": "Platform governance and operator documentation"},
    )
    doc_type, _ = ArtifactType.objects.get_or_create(
        slug="doc_page",
        defaults={
            "name": "Doc Page",
            "description": "Route-bound platform documentation",
            "icon": "FileText",
            "schema_json": {"fields": ["body_markdown", "tags", "route_bindings"]},
        },
    )

    def upsert_doc(slug: str, title: str, body: str, route_bindings: list[str], tags: list[str], visibility: str = "team"):
        artifact = Artifact.objects.filter(workspace=workspace, type=doc_type, slug=slug).first()
        if artifact is None:
            artifact = Artifact.objects.create(
                workspace=workspace,
                type=doc_type,
                title=title,
                slug=slug,
                status="published",
                version=1,
                visibility=visibility,
                scope_json={"slug": slug, "route_bindings": route_bindings},
                provenance_json={"source_system": "migration", "source_id": "0067"},
                published_at=timezone.now(),
            )
            ArtifactRevision.objects.create(
                artifact=artifact,
                revision_number=1,
                content_json={
                    "title": title,
                    "summary": "",
                    "body_markdown": body,
                    "tags": tags,
                },
            )
            ArtifactEvent.objects.create(
                artifact=artifact,
                event_type="doc_published",
                payload_json={"source": "migration"},
            )

    upsert_doc(
        slug="core-concepts",
        title="Core Concepts",
        body=CORE_CONCEPTS_MD,
        route_bindings=["app.home", "app.artifacts"],
        tags=["guide", "core-concepts"],
    )
    upsert_doc(
        slug="subscriber-notes-walkthrough",
        title="Subscriber Notes Walkthrough",
        body=SUBSCRIBER_NOTES_GUIDE_MD,
        route_bindings=["app.blueprints", "app.drafts", "app.release-plans", "app.instances", "app.runs"],
        tags=["guide", "subscriber-notes"],
    )


def _ensure_agent_defaults(apps, schema_editor):
    ModelProvider = apps.get_model("xyn_orchestrator", "ModelProvider")
    ModelConfig = apps.get_model("xyn_orchestrator", "ModelConfig")
    AgentPurpose = apps.get_model("xyn_orchestrator", "AgentPurpose")

    openai, _ = ModelProvider.objects.get_or_create(slug="openai", defaults={"name": "OpenAI", "enabled": True})
    ModelProvider.objects.get_or_create(slug="anthropic", defaults={"name": "Anthropic", "enabled": True})
    ModelProvider.objects.get_or_create(slug="google", defaults={"name": "Google", "enabled": False})

    cfg, _ = ModelConfig.objects.get_or_create(
        provider=openai,
        model_name="gpt-4o-mini",
        defaults={"temperature": 0.2, "max_tokens": 1200},
    )

    AgentPurpose.objects.get_or_create(
        slug="coding",
        defaults={"model_config": cfg, "system_prompt_markdown": "You are the coding assistant for Xyn.", "enabled": True},
    )
    AgentPurpose.objects.get_or_create(
        slug="documentation",
        defaults={
            "model_config": cfg,
            "system_prompt_markdown": "You are the documentation assistant for Xyn.",
            "enabled": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0066_rename_xyn_orchest_draft_a_4443de_idx_xyn_orchest_draft_a_aee5db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=160)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.IntegerField(default=1200)),
                ('top_p', models.FloatField(default=1.0)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider__slug', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('system_prompt_markdown', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_purposes_updated', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purposes', to='xyn_orchestrator.modelconfig')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_configs', to='xyn_orchestrator.modelprovider'),
        ),
        migrations.RunPython(_ensure_doc_pages, migrations.RunPython.noop),
        migrations.RunPython(_ensure_agent_defaults, migrations.RunPython.noop),
    ]
