# Generated by Codex on 2026-02-28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0086_video_adapter_registry_and_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="bindings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artifact",
            name="content_ref",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="dependencies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="artifact",
            name="package_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("reviewed", "Reviewed"),
                    ("ratified", "Ratified"),
                    ("published", "Published"),
                    ("deprecated", "Deprecated"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ArtifactPackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=240)),
                ("version", models.CharField(max_length=40)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("file_blob_ref", models.CharField(blank=True, default="", max_length=600)),
                ("package_hash", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_packages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "version", "package_hash")},
            },
        ),
        migrations.CreateModel(
            name="ArtifactBindingValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "binding_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("secret_ref", "Secret Ref"),
                            ("model_ref", "Model Ref"),
                            ("url", "URL"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "secret_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_bindings",
                        to="xyn_orchestrator.secretref",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_binding_values_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ArtifactInstallReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("package_name", models.CharField(max_length=240)),
                ("package_version", models.CharField(max_length=40)),
                ("package_hash", models.CharField(blank=True, default="", max_length=128)),
                ("installed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "install_mode",
                    models.CharField(
                        choices=[("install", "Install"), ("upgrade", "Upgrade"), ("reinstall", "Reinstall")],
                        default="install",
                        max_length=20,
                    ),
                ),
                ("resolved_bindings", models.JSONField(blank=True, default=dict)),
                ("operations", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed"), ("partial", "Partial")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_summary", models.TextField(blank=True, default="")),
                ("artifact_changes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifact_install_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="install_receipts",
                        to="xyn_orchestrator.artifactpackage",
                    ),
                ),
            ],
            options={"ordering": ["-installed_at"]},
        ),
    ]
