# Generated by Django 5.2.12 on 2026-03-18 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0122_devtask_execution_brief_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app_key', models.CharField(db_index=True, max_length=160)),
                ('category', models.CharField(choices=[('application', 'Application'), ('system', 'System')], db_index=True, default='application', max_length=40)),
                ('notification_type_key', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('deep_link', models.CharField(blank=True, default='', max_length=500)),
                ('source_entity_type', models.CharField(blank=True, default='', max_length=120)),
                ('source_entity_id', models.CharField(blank=True, default='', max_length=160)),
                ('source_metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_notifications_created', to='xyn_orchestrator.useridentity')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_notifications', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app_key', models.CharField(blank=True, default='', max_length=160)),
                ('notification_type_key', models.CharField(blank=True, default='', max_length=120)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preferences', to='xyn_orchestrator.useridentity')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_preferences', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email')], db_index=True, default='email', max_length=40)),
                ('address', models.CharField(max_length=320)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='unverified', max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_targets', to='xyn_orchestrator.useridentity')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='xyn_orchestrator.appnotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='xyn_orchestrator.useridentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email')], db_index=True, default='email', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=40)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=240)),
                ('error_text', models.TextField(blank=True, default='')),
                ('error_details_json', models.JSONField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='xyn_orchestrator.appnotification')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='xyn_orchestrator.deliverytarget')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_attempts', to='xyn_orchestrator.notificationrecipient')),
            ],
            options={
                'ordering': ['-attempted_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['workspace', 'created_at'], name='ix_app_notif_workspace_created'),
        ),
        migrations.AddIndex(
            model_name='appnotification',
            index=models.Index(fields=['source_app_key', 'notification_type_key'], name='ix_app_notif_source_type'),
        ),
        migrations.AddIndex(
            model_name='deliverypreference',
            index=models.Index(fields=['owner', 'workspace'], name='ix_dlv_pref_owner_ws'),
        ),
        migrations.AddIndex(
            model_name='deliverypreference',
            index=models.Index(fields=['owner', 'source_app_key'], name='ix_dlv_pref_owner_src'),
        ),
        migrations.AddConstraint(
            model_name='deliverypreference',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('owner', 'workspace', 'source_app_key', 'notification_type_key'), name='uniq_delivery_pref_owner_workspace_scope'),
        ),
        migrations.AddConstraint(
            model_name='deliverypreference',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('owner', 'source_app_key', 'notification_type_key'), name='uniq_delivery_pref_owner_global_scope'),
        ),
        migrations.AddIndex(
            model_name='deliverytarget',
            index=models.Index(fields=['owner', 'channel', 'enabled'], name='ix_dlv_tgt_owner_chan_en'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.UniqueConstraint(fields=('owner', 'channel', 'address'), name='uniq_delivery_target_owner_channel_address'),
        ),
        migrations.AddConstraint(
            model_name='deliverytarget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('owner', 'channel'), name='uniq_primary_delivery_target_owner_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['recipient', 'unread', 'created_at'], name='ix_notif_recipient_feed'),
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('notification', 'recipient'), name='uniq_notification_recipient'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['notification', 'status', 'attempted_at'], name='ix_dlv_attempt_notif_st'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['target', 'status', 'attempted_at'], name='ix_dlv_attempt_tgt_st'),
        ),
    ]
