# Generated by Django 5.2.12 on 2026-03-18 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0123_appnotification_deliverypreference_deliverytarget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="", max_length=80)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_types",
                        to="xyn_orchestrator.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["label", "key"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=240)),
                ("campaign_type", models.CharField(default="generic", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to="xyn_orchestrator.useridentity",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="xyn_orchestrator.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="campaigntype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("key",),
                name="uniq_campaign_type_global_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigntype",
            constraint=models.UniqueConstraint(fields=("workspace", "key"), name="uniq_campaign_type_workspace_key"),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(fields=("workspace", "slug"), name="uniq_campaign_workspace_slug"),
        ),
    ]
