# Generated by Django 5.1.5 on 2026-03-18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0124_campaign_and_campaigntype"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestrationPipeline",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="v1", max_length=40)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("max_concurrency", models.PositiveIntegerField(default=1)),
                ("stale_run_timeout_seconds", models.PositiveIntegerField(default=3600)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orchestration_pipelines",
                        to="xyn_orchestrator.useridentity",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_pipelines",
                        to="xyn_orchestrator.workspace",
                    ),
                ),
            ],
            options={"ordering": ["name", "key"]},
        ),
        migrations.CreateModel(
            name="OrchestrationJobDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_key", models.CharField(max_length=120)),
                ("stage_key", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("handler_key", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("only_if_upstream_changed", models.BooleanField(default=False)),
                ("runs_per_jurisdiction", models.BooleanField(default=False)),
                ("runs_per_source", models.BooleanField(default=False)),
                ("concurrency_limit", models.PositiveIntegerField(default=1)),
                ("retry_max_attempts", models.PositiveIntegerField(default=3)),
                ("backoff_initial_seconds", models.PositiveIntegerField(default=30)),
                ("backoff_max_seconds", models.PositiveIntegerField(default=1800)),
                ("backoff_multiplier", models.FloatField(default=2.0)),
                ("produces_artifact", models.BooleanField(default=False)),
                ("artifact_kind", models.CharField(blank=True, default="", max_length=120)),
                ("schedule_json", models.JSONField(blank=True, default=dict)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_definitions",
                        to="xyn_orchestrator.orchestrationpipeline",
                    ),
                ),
            ],
            options={"ordering": ["stage_key", "job_key"]},
        ),
        migrations.CreateModel(
            name="OrchestrationRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("rerun", "Rerun"),
                            ("event", "Event"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("trigger_key", models.CharField(blank=True, default="", max_length=120)),
                ("scope_jurisdiction", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("scope_source", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(blank=True, default="", max_length=240)),
                ("error_text", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestration_runs",
                        to="xyn_orchestrator.useridentity",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="xyn_orchestrator.orchestrationpipeline",
                    ),
                ),
                (
                    "rerun_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rerun_children",
                        to="xyn_orchestrator.orchestrationrun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_runs",
                        to="xyn_orchestrator.workspace",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrchestrationJobRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("canceled", "Canceled"),
                            ("stale", "Stale"),
                            ("waiting_retry", "Waiting Retry"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("upstream_changed", models.BooleanField(default=False)),
                ("skipped_reason", models.CharField(blank=True, default="", max_length=240)),
                ("summary", models.CharField(blank=True, default="", max_length=240)),
                ("error_text", models.TextField(blank=True, default="")),
                ("output_change_token", models.CharField(blank=True, default="", max_length=160)),
                ("output_json", models.JSONField(blank=True, default=dict)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_runs",
                        to="xyn_orchestrator.orchestrationjobdefinition",
                    ),
                ),
                (
                    "output_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestration_job_runs",
                        to="xyn_orchestrator.artifact",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_runs",
                        to="xyn_orchestrator.orchestrationrun",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="OrchestrationJobDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "downstream_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_dependencies",
                        to="xyn_orchestrator.orchestrationjobdefinition",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_dependencies",
                        to="xyn_orchestrator.orchestrationpipeline",
                    ),
                ),
                (
                    "upstream_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_dependencies",
                        to="xyn_orchestrator.orchestrationjobdefinition",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddConstraint(
            model_name="orchestrationpipeline",
            constraint=models.UniqueConstraint(fields=("workspace", "key"), name="uniq_orchestration_pipeline_workspace_key"),
        ),
        migrations.AddConstraint(
            model_name="orchestrationjobdefinition",
            constraint=models.UniqueConstraint(fields=("pipeline", "job_key"), name="uniq_orchestration_job_definition_key"),
        ),
        migrations.AddConstraint(
            model_name="orchestrationjobrun",
            constraint=models.UniqueConstraint(fields=("run", "job_definition"), name="uniq_orchestration_job_run_per_run"),
        ),
        migrations.AddConstraint(
            model_name="orchestrationjobdependency",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "upstream_job", "downstream_job"),
                name="uniq_orchestration_job_dependency",
            ),
        ),
        migrations.AddConstraint(
            model_name="orchestrationjobdependency",
            constraint=models.CheckConstraint(
                check=~models.Q(upstream_job=models.F("downstream_job")),
                name="check_orchestration_dependency_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationrun",
            index=models.Index(fields=["workspace", "pipeline", "status"], name="ix_orch_run_ws_pipeline_status"),
        ),
        migrations.AddIndex(
            model_name="orchestrationrun",
            index=models.Index(fields=["workspace", "created_at"], name="ix_orch_run_ws_created"),
        ),
        migrations.AddIndex(
            model_name="orchestrationjobrun",
            index=models.Index(fields=["run", "status"], name="ix_orch_job_run_run_status"),
        ),
        migrations.AddIndex(
            model_name="orchestrationjobrun",
            index=models.Index(fields=["status", "next_attempt_at"], name="ix_orch_job_run_status_retry"),
        ),
        migrations.AddIndex(
            model_name="orchestrationjobdependency",
            index=models.Index(fields=["pipeline", "downstream_job"], name="ix_orch_dependency_downstream"),
        ),
        migrations.AddIndex(
            model_name="orchestrationjobdependency",
            index=models.Index(fields=["pipeline", "upstream_job"], name="ix_orch_dependency_upstream"),
        ),
    ]
