# Generated by Django 5.2.12 on 2026-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0127_rename_orchestration_job_run_partition_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationrun',
            name='run_type',
            field=models.CharField(db_index=True, default='data_pipeline', max_length=80),
        ),
        migrations.AddField(
            model_name='orchestrationrun',
            name='target_ref_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='orchestrationrun',
            index=models.Index(fields=['workspace', 'run_type', 'created_at'], name='ix_orch_run_type_time'),
        ),
    ]
