# Generated by Django 5.2.12 on 2026-03-19 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0128_orchestrationrun_run_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMatchEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_a_namespace', models.CharField(max_length=120)),
                ('candidate_a_type', models.CharField(max_length=120)),
                ('candidate_a_id', models.CharField(max_length=200)),
                ('candidate_b_namespace', models.CharField(max_length=120)),
                ('candidate_b_type', models.CharField(max_length=120)),
                ('candidate_b_id', models.CharField(max_length=200)),
                ('candidate_a_ref_json', models.JSONField(blank=True, default=dict)),
                ('candidate_b_ref_json', models.JSONField(blank=True, default=dict)),
                ('strategy_key', models.CharField(db_index=True, max_length=120)),
                ('score', models.FloatField(default=0.0)),
                ('decision', models.CharField(choices=[('exact_match', 'Exact Match'), ('probable_match', 'Probable Match'), ('possible_match', 'Possible Match'), ('non_match', 'Non Match'), ('needs_review', 'Needs Review')], db_index=True, default='non_match', max_length=24)),
                ('confidence', models.CharField(db_index=True, default='none', max_length=24)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('chain_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_match_evaluations', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_match_evaluations', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'decision', 'created_at'], name='ix_rec_match_ws_decision_time'), models.Index(fields=['workspace', 'strategy_key', 'created_at'], name='ix_rec_match_ws_strategy_time'), models.Index(fields=['workspace', 'correlation_id', 'created_at'], name='ix_rec_match_ws_corr_time'), models.Index(fields=['workspace', 'chain_id', 'created_at'], name='ix_rec_match_ws_chain_time'), models.Index(fields=['workspace', 'candidate_a_namespace', 'candidate_a_type', 'candidate_a_id'], name='ix_rec_match_ws_a_ref'), models.Index(fields=['workspace', 'candidate_b_namespace', 'candidate_b_type', 'candidate_b_id'], name='ix_rec_match_ws_b_ref')],
            },
        ),
    ]
