# Generated by Django 5.2.12 on 2026-03-19 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0129_recordmatchevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=240)),
                ('source_type', models.CharField(default='generic', max_length=120)),
                ('source_mode', models.CharField(choices=[('file_upload', 'File Upload'), ('remote_url', 'Remote URL/File'), ('api_polling', 'API Polling'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('lifecycle_state', models.CharField(choices=[('registered', 'Registered'), ('inspected', 'Inspected'), ('mapped', 'Mapped'), ('validated', 'Validated'), ('active', 'Active'), ('failing', 'Failing'), ('paused', 'Paused')], db_index=True, default='registered', max_length=20)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('warning', 'Warning'), ('failing', 'Failing'), ('paused', 'Paused')], db_index=True, default='unknown', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('refresh_cadence_seconds', models.PositiveIntegerField(default=0)),
                ('orchestration_pipeline_key', models.CharField(blank=True, default='', max_length=120)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('last_inspected_at', models.DateTimeField(blank=True, null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_connectors', to='xyn_orchestrator.useridentity')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_connectors', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connectors', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceInspectionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='ok', max_length=20)),
                ('detected_format', models.CharField(blank=True, default='', max_length=80)),
                ('discovered_fields_json', models.JSONField(blank=True, default=list)),
                ('sample_metadata_json', models.JSONField(blank=True, default=dict)),
                ('validation_findings_json', models.JSONField(blank=True, default=list)),
                ('inspected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inspections', to='xyn_orchestrator.useridentity')),
                ('inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inspections', to='xyn_orchestrator.orchestrationrun')),
                ('source_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='xyn_orchestrator.sourceconnector')),
            ],
            options={
                'ordering': ['-inspected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('active', 'Active')], db_index=True, default='draft', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('field_mapping_json', models.JSONField(blank=True, default=dict)),
                ('transformation_hints_json', models.JSONField(blank=True, default=dict)),
                ('validation_state_json', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_mappings', to='xyn_orchestrator.useridentity')),
                ('source_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='xyn_orchestrator.sourceconnector')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_source_mappings', to='xyn_orchestrator.useridentity')),
                ('validation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_mapping_validations', to='xyn_orchestrator.orchestrationrun')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sourceconnector',
            index=models.Index(fields=['workspace', 'lifecycle_state'], name='ix_source_connector_state'),
        ),
        migrations.AddIndex(
            model_name='sourceconnector',
            index=models.Index(fields=['workspace', 'health_status'], name='ix_source_connector_health'),
        ),
        migrations.AddIndex(
            model_name='sourceconnector',
            index=models.Index(fields=['workspace', 'source_type', 'source_mode'], name='ix_source_connector_type_mode'),
        ),
        migrations.AddConstraint(
            model_name='sourceconnector',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='uniq_source_connector_workspace_key'),
        ),
        migrations.AddIndex(
            model_name='sourceinspectionprofile',
            index=models.Index(fields=['source_connector', 'inspected_at'], name='ix_source_inspection_time'),
        ),
        migrations.AddIndex(
            model_name='sourceinspectionprofile',
            index=models.Index(fields=['source_connector', 'status'], name='ix_source_inspection_status'),
        ),
        migrations.AddIndex(
            model_name='sourcemapping',
            index=models.Index(fields=['source_connector', 'status'], name='ix_source_mapping_status'),
        ),
        migrations.AddConstraint(
            model_name='sourcemapping',
            constraint=models.UniqueConstraint(fields=('source_connector', 'version'), name='uniq_source_mapping_version'),
        ),
        migrations.AddConstraint(
            model_name='sourcemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('source_connector',), name='uniq_source_mapping_current'),
        ),
    ]
