# Generated by Django 5.2.12 on 2026-03-19 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0130_sourceconnector_sourceinspectionprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifecycleTransition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lifecycle_name", models.CharField(db_index=True, max_length=128)),
                ("object_type", models.CharField(db_index=True, max_length=128)),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("from_state", models.CharField(blank=True, default="", max_length=64)),
                ("to_state", models.CharField(max_length=64)),
                ("actor", models.CharField(blank=True, default="", max_length=255)),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("correlation_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_transitions",
                        to="xyn_orchestrator.run",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lifecycle_transitions",
                        to="xyn_orchestrator.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="lifecycletransition",
            index=models.Index(fields=["workspace", "lifecycle_name"], name="ix_lifecycle_workspace_name"),
        ),
        migrations.AddIndex(
            model_name="lifecycletransition",
            index=models.Index(fields=["workspace", "object_type", "object_id"], name="ix_lifecycle_object_lookup"),
        ),
        migrations.AddIndex(
            model_name="lifecycletransition",
            index=models.Index(fields=["lifecycle_name", "object_type", "created_at"], name="ix_lifecycle_timeline"),
        ),
    ]
