# Generated by Django 5.2.12 on 2026-03-19 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0131_lifecycletransition'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=240)),
                ('target_kind', models.CharField(default='generic', max_length=120)),
                ('target_ref_json', models.JSONField(blank=True, default=dict)),
                ('filter_criteria_json', models.JSONField(blank=True, default=dict)),
                ('lifecycle_state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_watches', to='xyn_orchestrator.useridentity')),
                ('linked_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_watches', to='xyn_orchestrator.campaign')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchMatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(blank=True, default='', max_length=120)),
                ('matched', models.BooleanField(db_index=True, default=False)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('event_ref_json', models.JSONField(blank=True, default=dict)),
                ('filter_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('notification_intent_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('chain_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_match_events', to='xyn_orchestrator.orchestrationrun')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='xyn_orchestrator.watchdefinition')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_match_events', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WatchSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_type', models.CharField(choices=[('user_identity', 'User Identity'), ('delivery_target', 'Delivery Target'), ('external_endpoint', 'External Endpoint')], default='user_identity', max_length=40)),
                ('subscriber_ref', models.CharField(max_length=255)),
                ('destination_json', models.JSONField(blank=True, default=dict)),
                ('preferences_json', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_watch_subscribers', to='xyn_orchestrator.useridentity')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='xyn_orchestrator.watchdefinition')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='watchdefinition',
            index=models.Index(fields=['workspace', 'lifecycle_state'], name='ix_watch_workspace_state'),
        ),
        migrations.AddIndex(
            model_name='watchdefinition',
            index=models.Index(fields=['workspace', 'target_kind'], name='ix_watch_workspace_target'),
        ),
        migrations.AddConstraint(
            model_name='watchdefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='uniq_watch_workspace_key'),
        ),
        migrations.AddIndex(
            model_name='watchmatchevent',
            index=models.Index(fields=['workspace', 'watch', 'created_at'], name='ix_watch_match_timeline'),
        ),
        migrations.AddIndex(
            model_name='watchmatchevent',
            index=models.Index(fields=['workspace', 'matched', 'created_at'], name='ix_watch_match_workspace_state'),
        ),
        migrations.AddIndex(
            model_name='watchmatchevent',
            index=models.Index(fields=['workspace', 'correlation_id'], name='ix_watch_match_correlation'),
        ),
        migrations.AddIndex(
            model_name='watchmatchevent',
            index=models.Index(fields=['workspace', 'chain_id'], name='ix_watch_match_chain'),
        ),
        migrations.AddIndex(
            model_name='watchmatchevent',
            index=models.Index(fields=['workspace', 'event_key', 'created_at'], name='ix_watch_match_event'),
        ),
        migrations.AddIndex(
            model_name='watchsubscriber',
            index=models.Index(fields=['watch', 'enabled'], name='ix_watch_subscriber_enabled'),
        ),
        migrations.AddConstraint(
            model_name='watchsubscriber',
            constraint=models.UniqueConstraint(fields=('watch', 'subscriber_type', 'subscriber_ref'), name='uniq_watch_subscriber_ref'),
        ),
    ]
