# Generated by Django 5.2.12 on 2026-03-19 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0132_watchdefinition_watchmatchevent_watchsubscriber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=160)),
                ('subject_type', models.CharField(db_index=True, max_length=120)),
                ('subject_id', models.CharField(db_index=True, max_length=255)),
                ('subject_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('subject_ref_json', models.JSONField(blank=True, default=dict)),
                ('actor_type', models.CharField(blank=True, default='', max_length=120)),
                ('actor_id', models.CharField(blank=True, default='', max_length=255)),
                ('actor_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('actor_ref_json', models.JSONField(blank=True, default=dict)),
                ('cause_type', models.CharField(blank=True, default='', max_length=120)),
                ('cause_id', models.CharField(blank=True, default='', max_length=255)),
                ('cause_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('cause_ref_json', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, default='', max_length=280)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('chain_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_audit_events', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(db_index=True, max_length=160)),
                ('source_type', models.CharField(db_index=True, max_length=120)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('source_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('source_ref_json', models.JSONField(blank=True, default=dict)),
                ('target_type', models.CharField(db_index=True, max_length=120)),
                ('target_id', models.CharField(db_index=True, max_length=255)),
                ('target_namespace', models.CharField(blank=True, default='', max_length=120)),
                ('target_ref_json', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('chain_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('origin_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_links', to='xyn_orchestrator.platformauditevent')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_links', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_links', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['workspace', 'event_type', 'created_at'], name='ix_platform_audit_type_time'),
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['workspace', 'subject_type', 'subject_id', 'created_at'], name='ix_platform_audit_subject'),
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['workspace', 'correlation_id', 'created_at'], name='ix_platform_audit_corr'),
        ),
        migrations.AddIndex(
            model_name='platformauditevent',
            index=models.Index(fields=['workspace', 'chain_id', 'created_at'], name='ix_platform_audit_chain'),
        ),
        migrations.AddIndex(
            model_name='provenancelink',
            index=models.Index(fields=['workspace', 'source_type', 'source_id', 'created_at'], name='ix_prov_source_time'),
        ),
        migrations.AddIndex(
            model_name='provenancelink',
            index=models.Index(fields=['workspace', 'target_type', 'target_id', 'created_at'], name='ix_prov_target_time'),
        ),
        migrations.AddIndex(
            model_name='provenancelink',
            index=models.Index(fields=['workspace', 'relationship_type', 'created_at'], name='ix_prov_relationship_time'),
        ),
        migrations.AddIndex(
            model_name='provenancelink',
            index=models.Index(fields=['workspace', 'correlation_id', 'created_at'], name='ix_prov_corr_time'),
        ),
        migrations.AddIndex(
            model_name='provenancelink',
            index=models.Index(fields=['workspace', 'chain_id', 'created_at'], name='ix_prov_chain_time'),
        ),
    ]
