# Generated by Django 5.2.12 on 2026-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0133_platformauditevent_provenancelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='dispatch_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='platformauditevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='provenancelink',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='recordmatchevaluation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='recordmatchevaluation',
            name='pair_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sourceinspectionprofile',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='sourceinspectionprofile',
            name='inspection_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sourcemapping',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='sourcemapping',
            name='mapping_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='watchmatchevent',
            name='event_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='watchmatchevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddConstraint(
            model_name='appnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', ''), ('workspace__isnull', False)), fields=('workspace', 'source_app_key', 'notification_type_key', 'idempotency_key'), name='uniq_app_notif_workspace_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='appnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', ''), ('workspace__isnull', True)), fields=('source_app_key', 'notification_type_key', 'idempotency_key'), name='uniq_app_notif_global_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('dispatch_key__gt', '')), fields=('dispatch_key',), name='uniq_delivery_attempt_dispatch_key'),
        ),
        migrations.AddConstraint(
            model_name='platformauditevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_platform_audit_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='provenancelink',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_provenance_link_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='recordmatchevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_record_match_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='sourceinspectionprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('source_connector', 'idempotency_key'), name='uniq_source_inspection_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='sourcemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('source_connector', 'idempotency_key'), name='uniq_source_mapping_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='watchmatchevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'watch', 'idempotency_key'), name='uniq_watch_match_idempotency'),
        ),
    ]
