# Generated by Django 5.2.12 on 2026-03-19 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0134_appnotification_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationStagePublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(db_index=True, max_length=80)),
                ('stage_state', models.CharField(choices=[('completed', 'Completed'), ('published', 'Published')], db_index=True, default='completed', max_length=20)),
                ('scope_jurisdiction', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('scope_source', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('normalized_snapshot_ref', models.TextField(blank=True, default='')),
                ('normalized_change_token', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('reconciled_state_version', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('signal_set_version', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('publication_metadata_json', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_publication', to='xyn_orchestrator.orchestrationjobrun')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_publications', to='xyn_orchestrator.orchestrationpipeline')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_publications', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_stage_publications', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'pipeline', 'stage_key', 'scope_jurisdiction', 'scope_source', 'published_at'], name='ix_orch_stage_pub_partition'), models.Index(fields=['workspace', 'stage_key', 'published_at'], name='ix_orch_stage_pub_ws_stage'), models.Index(fields=['workspace', 'reconciled_state_version', 'published_at'], name='ix_orch_stage_pub_reconciled')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'pipeline', 'stage_key', 'run', 'scope_jurisdiction', 'scope_source', 'job_run'), name='uniq_orch_stage_pub_job')],
            },
        ),
    ]
