# Generated by Django 5.2.12 on 2026-03-19 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0135_orchestrationstagepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('event_status', models.CharField(choices=[('recorded', 'Recorded')], db_index=True, default='recorded', max_length=20)),
                ('stage_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('scope_jurisdiction', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('scope_source', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('subject_ref_json', models.JSONField(blank=True, default=dict)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('normalized_snapshot_ref', models.TextField(blank=True, default='')),
                ('normalized_change_token', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('reconciled_state_version', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('signal_set_version', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('chain_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_events', to='xyn_orchestrator.orchestrationjobrun')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_events', to='xyn_orchestrator.orchestrationpipeline')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_events', to='xyn_orchestrator.orchestrationstagepublication')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_events', to='xyn_orchestrator.orchestrationrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_domain_events', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'event_type', 'created_at'], name='ix_domain_event_type_time'), models.Index(fields=['workspace', 'stage_key', 'scope_jurisdiction', 'scope_source', 'created_at'], name='ix_domain_event_scope_time'), models.Index(fields=['workspace', 'pipeline', 'created_at'], name='ix_domain_event_pipeline_time'), models.Index(fields=['workspace', 'reconciled_state_version', 'created_at'], name='ix_domain_event_reconciled'), models.Index(fields=['workspace', 'signal_set_version', 'created_at'], name='ix_domain_event_signal')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_platform_domain_event_idempotency')],
            },
        ),
    ]
