# Generated by Django 5.2.12 on 2026-03-20 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0136_platformdomainevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestArtifactRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_id', models.UUIDField(db_index=True)),
                ('artifact_uri', models.TextField(blank=True, default='')),
                ('storage_provider', models.CharField(blank=True, default='', max_length=32)),
                ('storage_key', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('byte_length', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('snapshot_type', models.CharField(blank=True, default='', max_length=64)),
                ('retention_class', models.CharField(blank=True, default='', max_length=32)),
                ('scope_jurisdiction', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('scope_source', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifacts', to='xyn_orchestrator.orchestrationjobrun')),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifacts', to='xyn_orchestrator.orchestrationrun')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifacts', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_artifacts', to='xyn_orchestrator.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'artifact_id'], name='ix_ingest_artifact_workspace'), models.Index(fields=['workspace', 'snapshot_type'], name='ix_ingest_artifact_snapshot'), models.Index(fields=['workspace', 'retention_class'], name='ix_ingest_artifact_retention'), models.Index(fields=['workspace', 'created_at'], name='ix_ingest_artifact_created')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'artifact_id'), name='uniq_ingest_artifact_workspace')],
            },
        ),
    ]
