# Generated by Django 5.2.12 on 2026-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0139_watch_match_event_reconciled_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmatchevent',
            name='scope_jurisdiction',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
