# Generated by Django 5.2.12 on 2026-03-21 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0140_watchmatchevent_scope_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='final_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='last_modified',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestartifactrecord',
            name='source_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='IngestArtifactMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_path', models.TextField(blank=True, default='')),
                ('member_basename', models.CharField(blank=True, default='', max_length=255)),
                ('group_key', models.CharField(blank=True, default='', max_length=255)),
                ('extension', models.CharField(blank=True, default='', max_length=32)),
                ('classified_type', models.CharField(blank=True, default='', max_length=64)),
                ('byte_length', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('unsupported', 'Unsupported'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifact_members', to='xyn_orchestrator.orchestrationjobrun')),
                ('member_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_of', to='xyn_orchestrator.ingestartifactrecord')),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifact_members', to='xyn_orchestrator.orchestrationrun')),
                ('parent_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='xyn_orchestrator.ingestartifactrecord')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_artifact_members', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_artifact_members', to='xyn_orchestrator.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='IngestParsedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parser_name', models.CharField(blank=True, default='', max_length=120)),
                ('parser_version', models.CharField(blank=True, default='', max_length=64)),
                ('normalization_version', models.CharField(blank=True, default='', max_length=64)),
                ('record_index', models.IntegerField(blank=True, null=True)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_payload_json', models.JSONField(blank=True, default=dict)),
                ('source_schema_json', models.JSONField(blank=True, default=dict)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='ok', max_length=16)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_records', to='xyn_orchestrator.ingestartifactrecord')),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_parsed_records', to='xyn_orchestrator.orchestrationjobrun')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_records', to='xyn_orchestrator.ingestartifactmember')),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_parsed_records', to='xyn_orchestrator.orchestrationrun')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_records', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_parsed_records', to='xyn_orchestrator.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='ingestartifactmember',
            index=models.Index(fields=['workspace', 'parent_artifact'], name='ix_ing_member_parent'),
        ),
        migrations.AddIndex(
            model_name='ingestartifactmember',
            index=models.Index(fields=['workspace', 'group_key'], name='ix_ing_member_group'),
        ),
        migrations.AddIndex(
            model_name='ingestartifactmember',
            index=models.Index(fields=['workspace', 'classified_type'], name='ix_ing_member_class'),
        ),
        migrations.AddIndex(
            model_name='ingestartifactmember',
            index=models.Index(fields=['workspace', 'status'], name='ix_ing_member_status'),
        ),
        migrations.AddConstraint(
            model_name='ingestartifactmember',
            constraint=models.UniqueConstraint(fields=('parent_artifact', 'member_path'), name='uniq_ing_member_parent_path'),
        ),
        migrations.AddIndex(
            model_name='ingestparsedrecord',
            index=models.Index(fields=['workspace', 'orchestration_run'], name='ix_ing_parsed_run'),
        ),
        migrations.AddIndex(
            model_name='ingestparsedrecord',
            index=models.Index(fields=['workspace', 'artifact'], name='ix_ing_parsed_artifact'),
        ),
        migrations.AddIndex(
            model_name='ingestparsedrecord',
            index=models.Index(fields=['workspace', 'member'], name='ix_ing_parsed_member'),
        ),
        migrations.AddIndex(
            model_name='ingestparsedrecord',
            index=models.Index(fields=['workspace', 'parser_name'], name='ix_ing_parsed_parser'),
        ),
        migrations.AddIndex(
            model_name='ingestparsedrecord',
            index=models.Index(fields=['workspace', 'status'], name='ix_ing_parsed_status'),
        ),
        migrations.AddConstraint(
            model_name='ingestparsedrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_ing_parsed_idempotency'),
        ),
    ]
