# Generated by Django 5.2.12 on 2026-03-21 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0141_ingestartifactrecord_etag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestAdaptedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_name', models.CharField(blank=True, default='', max_length=120)),
                ('adapter_version', models.CharField(blank=True, default='', max_length=64)),
                ('adapter_kind', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_format', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_subtype', models.CharField(blank=True, default='', max_length=120)),
                ('record_index', models.IntegerField(blank=True, null=True)),
                ('adapted_payload_json', models.JSONField(blank=True, default=dict)),
                ('geometry_payload_json', models.JSONField(blank=True, default=dict)),
                ('field_metadata_json', models.JSONField(blank=True, default=list)),
                ('schema_hints_json', models.JSONField(blank=True, default=dict)),
                ('source_position_json', models.JSONField(blank=True, default=dict)),
                ('provenance_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('findings_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error'), ('unsupported', 'Unsupported')], default='ok', max_length=16)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapted_records', to='xyn_orchestrator.ingestartifactrecord')),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_adapted_records', to='xyn_orchestrator.orchestrationjobrun')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_records', to='xyn_orchestrator.ingestartifactmember')),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_adapted_records', to='xyn_orchestrator.orchestrationrun')),
                ('parsed_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_records', to='xyn_orchestrator.ingestparsedrecord')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_records', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_adapted_records', to='xyn_orchestrator.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'source_connector', 'created_at'], name='ix_ing_adapted_source_time'), models.Index(fields=['workspace', 'orchestration_run', 'created_at'], name='ix_ing_adapted_run_time'), models.Index(fields=['workspace', 'adapter_kind', 'created_at'], name='ix_ing_adapted_kind_time'), models.Index(fields=['workspace', 'source_format', 'created_at'], name='ix_ing_adapted_format_time'), models.Index(fields=['workspace', 'status', 'created_at'], name='ix_ing_adapted_status_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_ing_adapted_idempotency')],
            },
        ),
    ]
