# Generated by Django 5.2.12 on 2026-03-21 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0142_ingestadaptedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelCanonicalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_namespace', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('canonical_value_raw', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_value_normalized', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_identities', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelCrosswalkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('identifier_value_raw', models.CharField(blank=True, default='', max_length=255)),
                ('identifier_value_normalized', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('composite_key_normalized', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('unresolved', 'Unresolved'), ('deferred', 'Deferred'), ('superseded', 'Superseded')], db_index=True, default='resolved', max_length=20)),
                ('resolution_method', models.CharField(choices=[('deterministic_identifier', 'Deterministic Identifier'), ('deterministic_composite', 'Deterministic Composite'), ('address_fallback', 'Address Fallback'), ('deferred_geospatial', 'Deferred Geospatial'), ('unresolved', 'Unresolved')], db_index=True, default='deterministic_identifier', max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adapted_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_crosswalk_mappings', to='xyn_orchestrator.ingestadaptedrecord')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosswalk_mappings', to='xyn_orchestrator.parcelcanonicalidentity')),
                ('record_match_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_crosswalk_mappings', to='xyn_orchestrator.recordmatchevaluation')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_crosswalk_mappings', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_crosswalk_mappings', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelIdentifierAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(db_index=True, max_length=80)),
                ('value_raw', models.CharField(blank=True, default='', max_length=255)),
                ('value_normalized', models.CharField(db_index=True, max_length=255)),
                ('is_canonical', models.BooleanField(db_index=True, default=False)),
                ('confidence', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='xyn_orchestrator.parcelcanonicalidentity')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_identifier_aliases', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_identifier_aliases', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='parcelcanonicalidentity',
            index=models.Index(fields=['workspace', 'canonical_namespace', 'canonical_value_normalized'], name='ix_parcel_canon_lookup'),
        ),
        migrations.AddIndex(
            model_name='parcelcanonicalidentity',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='ix_parcel_canon_status_time'),
        ),
        migrations.AddIndex(
            model_name='parcelcrosswalkmapping',
            index=models.Index(fields=['workspace', 'source_connector', 'created_at'], name='ix_pcl_xw_src_time'),
        ),
        migrations.AddIndex(
            model_name='parcelcrosswalkmapping',
            index=models.Index(fields=['workspace', 'parcel', 'created_at'], name='ix_pcl_xw_par_time'),
        ),
        migrations.AddIndex(
            model_name='parcelcrosswalkmapping',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='ix_pcl_xw_st_time'),
        ),
        migrations.AddIndex(
            model_name='parcelcrosswalkmapping',
            index=models.Index(fields=['workspace', 'resolution_method', 'created_at'], name='ix_pcl_xw_mtd_time'),
        ),
        migrations.AddConstraint(
            model_name='parcelcrosswalkmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_parcel_crosswalk_idempotency'),
        ),
        migrations.AddIndex(
            model_name='parcelidentifieralias',
            index=models.Index(fields=['workspace', 'namespace', 'value_normalized'], name='ix_parcel_alias_lookup'),
        ),
        migrations.AddIndex(
            model_name='parcelidentifieralias',
            index=models.Index(fields=['workspace', 'parcel', 'namespace'], name='ix_parcel_alias_parcel_ns'),
        ),
        migrations.AddIndex(
            model_name='parcelidentifieralias',
            index=models.Index(fields=['workspace', 'source_connector', 'created_at'], name='ix_parcel_alias_source_time'),
        ),
        migrations.AddConstraint(
            model_name='parcelidentifieralias',
            constraint=models.UniqueConstraint(fields=('workspace', 'namespace', 'value_normalized', 'parcel'), name='uniq_parcel_alias_value_per_parcel'),
        ),
        migrations.AddConstraint(
            model_name='parcelidentifieralias',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('workspace', 'parcel', 'namespace'), name='uniq_parcel_alias_canonical_per_namespace'),
        ),
    ]
