# Generated by Django 5.2.12 on 2026-03-21 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0143_parcelcanonicalidentity_parcelcrosswalkmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeEnrichmentCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_rank', models.PositiveIntegerField(default=1)),
                ('provider_score', models.FloatField(blank=True, null=True)),
                ('provider_confidence', models.FloatField(blank=True, null=True)),
                ('matched_label', models.CharField(blank=True, default='', max_length=300)),
                ('matched_address', models.CharField(blank=True, default='', max_length=500)),
                ('geometry_json', models.JSONField(blank=True, default=dict)),
                ('spatial_reference_json', models.JSONField(blank=True, default=dict)),
                ('provider_attributes_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning')], default='ok', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['candidate_rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeEnrichmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_kind', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('provider_version', models.CharField(blank=True, default='', max_length=64)),
                ('provider_endpoint_url', models.TextField(blank=True, default='')),
                ('input_address_raw', models.TextField(blank=True, default='')),
                ('input_address_normalized', models.TextField(blank=True, db_index=True, default='')),
                ('input_address_fields_json', models.JSONField(blank=True, default=dict)),
                ('request_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('no_selection', 'No Selection'), ('no_candidates', 'No Candidates'), ('invalid_input', 'Invalid Input'), ('provider_not_configured', 'Provider Not Configured'), ('provider_error', 'Provider Error'), ('shape_error', 'Shape Error')], db_index=True, default='no_selection', max_length=32)),
                ('selection_reason', models.CharField(blank=True, default='', max_length=120)),
                ('request_context_json', models.JSONField(blank=True, default=dict)),
                ('response_context_json', models.JSONField(blank=True, default=dict)),
                ('failure_category', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adapted_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_enrichment_results', to='xyn_orchestrator.ingestadaptedrecord')),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_enrichment_results', to='xyn_orchestrator.orchestrationjobrun')),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_enrichment_results', to='xyn_orchestrator.orchestrationrun')),
                ('selected_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_result_sets', to='xyn_orchestrator.geocodeenrichmentcandidate')),
                ('source_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_enrichment_results', to='xyn_orchestrator.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocode_enrichment_results', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='geocodeenrichmentcandidate',
            name='result_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='xyn_orchestrator.geocodeenrichmentresult'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentresult',
            index=models.Index(fields=['workspace', 'source_connector', 'created_at'], name='ix_geo_res_src_time'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentresult',
            index=models.Index(fields=['workspace', 'orchestration_run', 'created_at'], name='ix_geo_res_run_time'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentresult',
            index=models.Index(fields=['workspace', 'adapted_record', 'created_at'], name='ix_geo_res_adp_time'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentresult',
            index=models.Index(fields=['workspace', 'provider_kind', 'created_at'], name='ix_geo_res_kind_time'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentresult',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='ix_geo_res_status_t'),
        ),
        migrations.AddConstraint(
            model_name='geocodeenrichmentresult',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workspace', 'idempotency_key'), name='uniq_geocode_result_idempotency'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentcandidate',
            index=models.Index(fields=['result_set', 'candidate_rank'], name='ix_geo_cand_rank'),
        ),
        migrations.AddIndex(
            model_name='geocodeenrichmentcandidate',
            index=models.Index(fields=['result_set', 'is_selected'], name='ix_geo_cand_sel'),
        ),
        migrations.AddConstraint(
            model_name='geocodeenrichmentcandidate',
            constraint=models.UniqueConstraint(fields=('result_set', 'candidate_rank'), name='uniq_geocode_candidate_rank'),
        ),
        migrations.AddConstraint(
            model_name='geocodeenrichmentcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('result_set',), name='uniq_geocode_selected_candidate'),
        ),
    ]
