# Generated by Django 5.2.12 on 2026-03-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0144_geocodeenrichmentcandidate_geocodeenrichmentresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnector',
            name='governance_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sourceconnector',
            name='review_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sourceconnector',
            name='review_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceconnector',
            name='review_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_source_connectors', to='xyn_orchestrator.useridentity'),
        ),
    ]
