# Generated by Django 5.2.12 on 2026-03-25 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0149_solutionchangesession_execution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPlanningCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('required_before', models.CharField(choices=[('stage', 'Stage'), ('apply', 'Apply'), ('dispatch', 'Dispatch')], default='stage', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_planning_checkpoint_decisions', to='xyn_orchestrator.useridentity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_checkpoints', to='xyn_orchestrator.solutionchangesession')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_planning_checkpoints', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'checkpoint_key', 'required_before'), name='uniq_solution_planning_checkpoint_key_scope')],
            },
        ),
        migrations.CreateModel(
            name='SolutionPlanningTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(choices=[('user', 'User'), ('planner', 'Planner')], max_length=16)),
                ('kind', models.CharField(choices=[('request', 'Request'), ('question', 'Question'), ('option_set', 'Option Set'), ('draft_plan', 'Draft Plan'), ('checkpoint', 'Checkpoint'), ('response', 'Response'), ('approval', 'Approval')], max_length=24)),
                ('sequence', models.IntegerField(default=1)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_planning_turns', to='xyn_orchestrator.useridentity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_turns', to='xyn_orchestrator.solutionchangesession')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_planning_turns', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_solution_planning_turn_sequence')],
            },
        ),
    ]
