# Generated by Django 5.2.12 on 2026-04-04 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0156_solutionchangesession_execution_status_committed_promoted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionChangeSessionPromotionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('promotion', 'Promotion')], default='promotion', max_length=24)),
                ('promotion_status', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='success', max_length=20)),
                ('actor_source', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('system', 'System')], default='human', max_length=20)),
                ('targeted_artifacts_json', models.JSONField(blank=True, default=list)),
                ('preview_target_json', models.JSONField(blank=True, default=dict)),
                ('root_target_json', models.JSONField(blank=True, default=dict)),
                ('resulting_active_target_json', models.JSONField(blank=True, default=dict)),
                ('superseded_active_state_json', models.JSONField(blank=True, default=dict)),
                ('control_result_json', models.JSONField(blank=True, default=dict)),
                ('provider_context_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('blocked_context_json', models.JSONField(blank=True, default=dict)),
                ('rollback_link_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_change_session_promotion_evidence', to='xyn_orchestrator.useridentity')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_evidence', to='xyn_orchestrator.application')),
                ('solution_change_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_evidence', to='xyn_orchestrator.solutionchangesession')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_change_session_promotion_evidence', to='xyn_orchestrator.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
