# Generated by Django 5.2.12 on 2026-04-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyn_orchestrator', '0157_solutionchangesessionpromotionevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionchangesessionpromotionevidence',
            name='source_promotion_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_evidence', to='xyn_orchestrator.solutionchangesessionpromotionevidence'),
        ),
        migrations.AlterField(
            model_name='solutionchangesessionpromotionevidence',
            name='operation',
            field=models.CharField(choices=[('promotion', 'Promotion'), ('rollback', 'Rollback')], default='promotion', max_length=24),
        ),
    ]
