# Generated by Django 5.2.12 on 2026-04-04 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0158_solutionchangesessionpromotionevidence_source_promotion_evidence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseTargetDeploymentPreparationEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("planning_mode", models.CharField(blank=True, default="", max_length=40)),
                ("operation", models.CharField(blank=True, default="", max_length=120)),
                ("provider_key", models.CharField(blank=True, default="", max_length=120)),
                ("provider_module_contract_ref", models.CharField(blank=True, default="", max_length=255)),
                ("execution_ready_in_principle", models.BooleanField(default=False)),
                ("mutation_performed", models.BooleanField(default=False)),
                ("requested_config_json", models.JSONField(blank=True, default=dict)),
                ("discovered_inputs_json", models.JSONField(blank=True, default=list)),
                ("missing_inputs_json", models.JSONField(blank=True, default=list)),
                ("steps_json", models.JSONField(blank=True, default=list)),
                ("warnings_json", models.JSONField(blank=True, default=list)),
                ("staged_execution_intent_json", models.JSONField(blank=True, default=dict)),
                ("plan_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_target_deployment_preparation_evidence",
                        to="xyn_orchestrator.blueprint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_target_deployment_preparation_evidence_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_preparation_evidence",
                        to="xyn_orchestrator.releasetarget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["release_target", "created_at"], name="ix_rt_prep_target_time"),
                    models.Index(fields=["provider_key", "created_at"], name="ix_rt_prep_provider_time"),
                ],
            },
        ),
    ]
