# Generated by Django 5.2.12 on 2026-04-04 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xyn_orchestrator", "0159_releasetargetdeploymentpreparationevidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseTargetExecutionPreparationHandoff",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("ready", "Ready"), ("blocked", "Blocked"), ("invalid", "Invalid")],
                        default="blocked",
                        max_length=20,
                    ),
                ),
                ("blocked_reason", models.CharField(blank=True, default="", max_length=120)),
                ("mutation_performed", models.BooleanField(default=False)),
                ("handoff_json", models.JSONField(blank=True, default=dict)),
                ("warnings_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_target_execution_preparation_handoffs",
                        to="xyn_orchestrator.blueprint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_target_execution_preparation_handoffs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_preparation_handoffs",
                        to="xyn_orchestrator.releasetarget",
                    ),
                ),
                (
                    "source_preparation_evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_preparation_handoffs",
                        to="xyn_orchestrator.releasetargetdeploymentpreparationevidence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["release_target", "created_at"], name="ix_rt_exec_handoff_target_time"),
                    models.Index(fields=["validation_status", "created_at"], name="ix_rt_exec_handoff_status_time"),
                ],
            },
        ),
    ]
