# Generated by Django 5.2.10 on 2026-01-29 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('page', 'Page'), ('articles_index', 'Articles index'), ('external', 'External'), ('route', 'Route')], default='page', max_length=30)),
                ('external_url', models.URLField(blank=True)),
                ('requires_auth', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='web.page')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WebSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('feature_grid', 'Feature grid'), ('service_cards', 'Service cards'), ('cta_band', 'CTA band'), ('quote', 'Quote'), ('simple_md', 'Simple markdown')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body_md', models.TextField(blank=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.page')),
            ],
            options={
                'ordering': ['order', 'key'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
